/* Phase 3: heartbeat JSON rendering + permission-prompt modal.
 *
 * Architecture:
 *   - BLE RX callback (BLE thread) pushes raw bytes into a FuriStreamBuffer.
 *   - A dedicated drain thread accumulates bytes into a line buffer, parses
 *     one JSON object per '\n' with jsmn, and updates shared app state
 *     under a mutex.
 *   - The main thread drives the GUI: a redraw timer at 4 Hz polls state
 *     and repaints, and an input queue handles button events.
 *   - When the parsed heartbeat contains a `prompt` object, the app enters
 *     ModePrompt and renders a modal with tool/hint + keybindings. OK and
 *     Left send the permission response back via TX; the desktop clears
 *     the prompt from subsequent heartbeats, which drops us back to
 *     ModeNormal.
 */

#include "claude_buddy_profile.h"

#include <furi.h>
#include <furi_hal_version.h>
#include <bt/bt_service/bt.h>
#include <gui/gui.h>
#include <gui/view_port.h>
#include <input/input.h>
#include <notification/notification_messages.h>
#include <gui/icon_animation.h>
#include <furi_hal_power.h>
#include <storage/storage.h>

/* Generated by the build from PNGs under claude_buddy/assets/ — exposes
 * the compiled Icon symbols. Animated subdirs (with a frame_rate file)
 * produce A_* Icons; each is wrapped in an IconAnimation at runtime. */
#include "claude_buddy_icons.h"

#define JSMN_STATIC
#include "jsmn.h"

#include <stdlib.h>
#include <string.h>

#define TAG "ClaudeBuddyApp"

#define REDRAW_PERIOD_MS    250
#define LINE_BUF_SIZE       1024
#define RX_STREAM_SIZE      2048
#define RX_STREAM_TRIGGER   1
#define RX_THREAD_STACK     2048
#define MAX_TOKENS          64

typedef enum {
    ClaudeBuddyModeNormal,
    ClaudeBuddyModePrompt,
} ClaudeBuddyMode;

/* Visible pet state. Derived from BT state + heartbeat counts + local
 * tracking (streaks, transients, battery, tamagotchi stats). Priority
 * order (top wins) in pet_state_derive() below. */
typedef enum {
    PetStateSleep,        /* disconnected, or nothing open on desktop */
    PetStateIdle,         /* connected, sessions open but not generating */
    PetStateBusy,         /* running > 0 */
    PetStateOverloaded,   /* running > 0 && total >= 5 */
    PetStateAttention,    /* waiting > 0 or modal open */
    PetStateHeart,        /* transient: approved within 5s of prompt */
    PetStateCelebrate,    /* transient: tokens crossed 10k milestone */
    PetStateReconnecting, /* transient: was Connected, now Advertising */
    PetStateHappy,        /* 3+ consecutive approvals (mood) */
    PetStateGrumpy,       /* 2+ consecutive denials (mood) */
    /* Tamagotchi-layer moods (Phase 5e): play/feed stats drive these.
     * Longer horizon than approval streaks — persist across prompt
     * decisions, decay over minutes. */
    PetStateContent,      /* play+feed both high */
    PetStateFocused,      /* feed high, play low — quietly at work */
    PetStateLonely,       /* both low, sustained */
    PetStateStarving,     /* feed == 0 for extended period */
    PetStateCount,
} PetState;

/* Life stages. age_transactions drives which sprite set we use for
 * a given PetState (Phase 5g evolution). */
typedef enum {
    EvoEgg = 0,   /* ages 0..9, no limbs, peek-a-boo through crack */
    EvoChild,     /* ages 10..49, current baseline boxy mascot */
    EvoTeen,      /* ages 50..199, taller with hair tuft */
    EvoAdult,     /* ages 200..999, fuller with belt detail */
    EvoElder,     /* ages 1000+, wizard hat + evolved form */
    EvoCount,
} PetEvoStage;

#define TOKENS_MILESTONE         (10000u)
#define HEART_TRIGGER_MS         (5000u)
#define HEART_LINGER_MS          (5000u)
#define CELEBRATE_LINGER_MS      (5000u)
#define RECONNECTING_LINGER_MS   (8000u)
/* Full-screen evolution cinematic duration. 12 frames @ 4 FPS = 3s
 * anim; give a tiny margin so the last frame renders before teardown. */
#define EVOLUTION_LINGER_MS      (3200u)
/* "Claudochi used X!" narration box stays up this long after an OK
 * confirm before the modal fully closes. Pokemon-game dramatic
 * pause. Input is swallowed during the phase. */
#define NARRATION_LINGER_MS      (1500u)
#define HAPPY_STREAK             (3)
#define GRUMPY_STREAK            (2)
#define LOW_BATTERY_PCT          (20)

/* Tamagotchi tuning */
#define LEVEL_MAX                (1000u)
#define PLAY_HIGH                (500u)
#define PLAY_LOW                 (200u)
#define FEED_HIGH                (500u)
#define FEED_LOW                 (200u)
#define CLASSIFY_WINDOW_MS       (30000u)  /* msg → tool-call window */
/* Direct tokens → feed scaling. The split-A msg-classifier only credits
 * feed when an UNLABELED msg change is followed by tokens growth — in
 * practice tool-heavy sessions emit "running:"/"done(...)" labels for
 * every msg, so the classifier rarely fires and feed sits empty while
 * play climbs (each msg change = play bump). Crediting feed directly
 * from tokens delta covers the common case: Claude actually doing work
 * feeds the pet, regardless of what msg says. */
#define FEED_TOKENS_PER_UNIT     (8u)      /* 80 tokens → 10 feed */
#define FEED_GAIN_CAP_PER_HB     (100u)    /* hard cap per heartbeat */
/* Explicit approvals feed the pet — each "yes, go do this tool" is a
 * deliberate user intent to spend compute, which thematically = food.
 * Larger than a typical single-heartbeat tokens credit (cap 30/hb)
 * because an approval is a discrete user decision, not a continuous
 * signal; it earns its own step up. 10 approvals from empty → above
 * FEED_HIGH (500). Denials give zero — no feed for "no". */
#define FEED_PER_APPROVAL        (50u)
/* Cap the credit a single classified msg change can add to play or
 * feed. Without this, raw byte-count crediting made the Happy bar
 * fill in ~5 messages — longer user prompts (100+ bytes each) blew
 * past PLAY_HIGH before the pet registered any meaningful playtime.
 * With the cap, a 10-byte "ok" still contributes less than a 15-byte
 * thoughtful reply, but a 200-byte paragraph doesn't spike the bar. */
#define MSG_CLASSIFY_CAP         (15u)
#define DECAY_TICK_MS            (60000u)  /* decay once per minute */
#define PLAY_DECAY_PER_MIN       (2u)
#define FEED_DECAY_PER_MIN       (1u)
#define LONELY_SUSTAIN_MS        (90000u)  /* 90s of low-low = lonely */
#define STARVING_SUSTAIN_MS      (300000u) /* 5min of zero feed = starving */
#define AUTOSAVE_INTERVAL_MS     (300000u) /* save every 5 min */

/* Persistence — state survives across app restarts. */
#define CB_STATE_MAGIC           (0x43424450u)  /* "CBDP" */
#define CB_STATE_VERSION         (1u)
#define CB_STATE_DIR             "/ext/apps_data/claude_buddy"
#define CB_STATE_PATH            "/ext/apps_data/claude_buddy/state.bin"

typedef struct {
    uint32_t magic;
    uint32_t version;
    uint32_t play_level;
    uint32_t feed_level;
    uint32_t age_transactions;
    uint32_t total_approvals;
    uint32_t total_denials;
    uint32_t interaction_bytes;
    uint32_t last_saved_ms;
    uint32_t reserved[6];
} ClaudeBuddyPersist;

typedef struct {
    FuriMutex* mtx;

    /* BT status */
    BtStatus bt_status;
    bool cccd_enabled;

    /* Parsed heartbeat fields */
    int hb_total;
    int hb_running;
    int hb_waiting;
    char hb_msg[64];

    /* Prompt state (valid when mode == Prompt) */
    ClaudeBuddyMode mode;
    char prompt_id[48];
    char prompt_tool[32];
    char prompt_hint[96]; /* parsed but not rendered — Pokemon modal has no room */
    /* Pokemon-style action row cursor. col=0 selects ONCE, col=1
     * selects DENY. Reset to 0 on each new prompt. Only `once` and
     * `deny` are valid decisions per REFERENCE.md. */
    uint8_t prompt_cursor_col;
    /* Narration phase — plays after OK, outlives heartbeat
     * prompt-clear. When narration_until_ms > now, the modal shows
     * "Claudochi used X!" instead of the action grid, and all input
     * is swallowed so the text box can't be interrupted. */
    uint32_t narration_until_ms;
    char narration_decision[16]; /* "once" | "deny" */

    /* GUI */
    FuriMessageQueue* input_queue;
    ViewPort* view_port;
    Gui* gui;
    FuriTimer* redraw_timer;

    /* RX pipeline */
    FuriStreamBuffer* rx_stream;
    FuriThread* rx_thread;
    volatile bool running;
    uint8_t line_buf[LINE_BUF_SIZE];
    size_t line_len;

    /* BT service + active profile */
    Bt* bt;
    FuriHalBleProfileBase* profile;

    /* LED / haptic */
    NotificationApp* notifications;

    /* Currently-playing mascot animation. Swapped by ensure_anim()
     * when the derived pet state OR life stage changes. Guarded by
     * app->mtx. */
    IconAnimation* current_anim;
    PetState anim_state;
    PetEvoStage anim_stage;
    /* First call to ensure_anim shouldn't treat the startup state as
     * a stage transition. This flips to true at the end of the first
     * call so subsequent stage changes (age crossing 10/100/1000/3000)
     * correctly fire the evolution cinematic. */
    bool anim_initialized;

    /* Full-screen evolution animation — plays briefly when the pet
     * crosses a stage boundary. Allocated on transition, freed when
     * the timer expires. NULL during normal operation. */
    IconAnimation* evolve_anim;
    uint32_t evolve_until_ms;

    /* Tokens milestone tracking — celebrate when `tokens` jumps past
     * the next 10k mark. last_celebrated seeded on first heartbeat so
     * we don't celebrate mid-session tokens at app start. */
    int hb_tokens;
    int last_celebrated_tokens;
    bool tokens_baseline_set;

    /* Transient overrides (heart / celebrate / reconnecting).
     * transient_until_ms == 0 means no transient is active. */
    PetState transient_state;
    uint32_t transient_until_ms;
    uint32_t prompt_shown_at_ms; /* reset when a prompt first appears */

    /* Streak counters driven by the prompt input handler. */
    int approval_streak;
    int denial_streak;

    /* Reconnecting detection — fires when we go Connected → Advertising.
     * We deliberately don't reset on subsequent states so repeated
     * reconnects keep triggering. */
    bool was_connected;

    /* Claudegotchi substrate — unrecognized msg arrivals (user typing,
     * narrative text, anything that doesn't match summarize_msg's
     * status ladder) feed into these counters. We don't render the
     * content; just acknowledge the activity with a pulsing "…"
     * indicator and accumulate for the Phase 5e play/feed mechanics. */
    uint32_t last_activity_ms;
    uint32_t interaction_bytes;

    /* Play/feed levels, each 0..LEVEL_MAX. Drive Content/Focused/
     * Lonely/Starving mood states. Phase 5e.1 in-memory only; Phase
     * 5e.2 will persist them to SD. */
    uint32_t play_level;
    uint32_t feed_level;

    /* Pending classification window: when an unrecognized msg arrives,
     * we stamp it here. If tokens grow within CLASSIFY_WINDOW_MS, it's
     * credited to feed (Claude worked on the input). If the window
     * expires without tokens growth, it's credited to play (just
     * chatter). Single-slot; a new msg change while pending exists
     * forces classification of the old one first. */
    uint32_t pending_msg_ts;
    uint32_t pending_msg_bytes;
    int pending_start_tokens;

    /* Sustained-state tracking for Lonely/Starving mood triggers. */
    uint32_t lonely_since_ms;
    uint32_t starving_since_ms;
    uint32_t last_decay_ms;

    /* Lifetime counters, persisted to SD. age_transactions is the pet's
     * "age" — bumps on every classified interaction. total_approvals
     * and total_denials are lifetime button totals; approval_streak /
     * denial_streak above are session-scoped. */
    uint32_t age_transactions;
    uint32_t total_approvals;
    uint32_t total_denials;

    /* Autosave: periodically flush state to SD so an unplanned exit
     * doesn't lose progress. Milestones also trigger an immediate save. */
    uint32_t last_save_ms;

    /* Konami-code reset: tracks how many correct keys of the sequence
     * have been pressed in order. On full match, resets the pet. */
    uint8_t konami_progress;
} ClaudeBuddyApp;

/* Forward so callbacks can reference the struct. */
static void ensure_anim(ClaudeBuddyApp* app, PetState s);
/* claudegotchi_reset calls persist_save before its definition below. */
static void persist_save(ClaudeBuddyApp* app);

/* ============================================================
 *  JSON helpers — small wrappers on jsmn
 * ============================================================ */

static bool tok_streq(const char* json, const jsmntok_t* t, const char* s) {
    int len = t->end - t->start;
    return (int)strlen(s) == len && strncmp(json + t->start, s, len) == 0;
}

/* Linear key search: find the first STRING token matching `key` and
 * return the index of the immediately following (value) token. Good
 * enough for the Hardware Buddy heartbeat since all keys we care about
 * are globally unique across the object (total/running/waiting/msg at
 * top level; id/tool/hint only under `prompt`). Returns -1 if not
 * found. */
static int json_find_key(const char* json, const jsmntok_t* tokens, int n, const char* key) {
    for(int i = 0; i < n - 1; i++) {
        if(tokens[i].type == JSMN_STRING && tok_streq(json, &tokens[i], key)) {
            return i + 1;
        }
    }
    return -1;
}

static int json_tok_int(const char* json, const jsmntok_t* t) {
    char buf[16] = {0};
    int len = t->end - t->start;
    if(len < 0 || len >= (int)sizeof(buf)) return 0;
    memcpy(buf, json + t->start, len);
    return atoi(buf);
}

static void
    json_tok_strcpy(const char* json, const jsmntok_t* t, char* dst, size_t dst_size) {
    int len = t->end - t->start;
    if(len < 0) len = 0;
    if(len >= (int)dst_size) len = dst_size - 1;
    memcpy(dst, json + t->start, len);
    dst[len] = '\0';
}

/* Summarize a free-form heartbeat `msg` string into a short label
 * (≤ 5 chars) plus an optional detail word. The desktop's msg field is
 * "one-line summary suitable for a small display" per REFERENCE.md, but
 * in practice still too long for 64 px of right-column font-secondary.
 * Common observed patterns:
 *     "running: yarn test"      → RUN / yarn
 *     "approve: Bash"           → ASK / Bash
 *     "called bash"             → RUN / bash
 *     "done(success), 1 turns"  → DONE
 *     "done(failure), …"        → FAIL
 *     "approved"                → OK
 *     <anything else>           → raw msg in detail, no label
 * Extend the ladder here as new desktop patterns surface. */
typedef struct {
    char label[8];    /* 1-5 char summary, rendered in FontPrimary */
    char detail[24];  /* optional trailing word(s), FontSecondary */
} ClaudeBuddyMsgSummary;

static void copy_first_word(const char* src, char* dst, size_t dst_size) {
    while(*src == ' ') src++;
    size_t n = 0;
    while(*src && *src != ' ' && n < dst_size - 1) {
        dst[n++] = *src++;
    }
    dst[n] = '\0';
}

static void summarize_msg(const char* raw, ClaudeBuddyMsgSummary* s) {
    s->label[0] = '\0';
    s->detail[0] = '\0';
    if(!raw || !raw[0]) return;

    /* Desktop sometimes wraps msg in parens, e.g. "(called Bash)".
     * Strip a leading "(" so pattern matching works uniformly. */
    const char* p = raw;
    if(*p == '(') p++;

    if(strncmp(p, "running:", 8) == 0) {
        strlcpy(s->label, "RUN", sizeof(s->label));
        copy_first_word(p + 8, s->detail, sizeof(s->detail));
    } else if(strncmp(p, "approve:", 8) == 0) {
        strlcpy(s->label, "ASK", sizeof(s->label));
        copy_first_word(p + 8, s->detail, sizeof(s->detail));
    } else if(strncmp(p, "called ", 7) == 0) {
        strlcpy(s->label, "RUN", sizeof(s->label));
        copy_first_word(p + 7, s->detail, sizeof(s->detail));
    } else if(strncmp(p, "done(success", 12) == 0) {
        strlcpy(s->label, "DONE", sizeof(s->label));
    } else if(
        strncmp(p, "done(failure", 12) == 0 || strncmp(p, "done(error", 10) == 0 ||
        strncmp(p, "failed", 6) == 0) {
        strlcpy(s->label, "FAIL", sizeof(s->label));
    } else if(strcmp(p, "approved") == 0) {
        strlcpy(s->label, "OK", sizeof(s->label));
    } else if(strcmp(p, "denied") == 0) {
        strlcpy(s->label, "NO", sizeof(s->label));
    } else {
        /* Unknown pattern — show the raw text truncated, no label. */
        strlcpy(s->detail, raw, sizeof(s->detail));
    }

    /* Trim a trailing ")" that the paren-wrap leaves behind in detail. */
    size_t n = strlen(s->detail);
    if(n > 0 && s->detail[n - 1] == ')') s->detail[n - 1] = '\0';
}

/* Full pet state derivation — priority order (first match wins):
 *    1. Attention   — prompt pending
 *    2. Transient   — heart / celebrate / reconnecting within linger
 *    3. Starving    — feed == 0 for STARVING_SUSTAIN_MS (critical)
 *    4. Sleep       — BT not connected
 *    5. Overloaded  — running > 0 && total >= 5
 *    6. Busy        — running > 0
 *    7. Grumpy      — denial_streak >= GRUMPY_STREAK  (short-horizon UX)
 *    8. Happy       — approval_streak >= HAPPY_STREAK (short-horizon UX)
 *    9. Content     — play & feed both high           (long-horizon mood)
 *   10. Focused     — feed high, play low             (long-horizon mood)
 *   11. Lonely      — both low for LONELY_SUSTAIN_MS  (long-horizon mood)
 *   12. Idle        — connected with sessions
 *   13. Sleep       — default (no sessions)
 * Caller must hold app->mtx. */
static PetState pet_state_derive(const ClaudeBuddyApp* app) {
    if(app->mode == ClaudeBuddyModePrompt || app->hb_waiting > 0) {
        return PetStateAttention;
    }
    uint32_t now = furi_get_tick();
    if(app->transient_until_ms && now < app->transient_until_ms) {
        return app->transient_state;
    }
    if(app->starving_since_ms && now - app->starving_since_ms > STARVING_SUSTAIN_MS) {
        return PetStateStarving;
    }
    if(app->bt_status != BtStatusConnected) return PetStateSleep;
    if(app->hb_running > 0) {
        return (app->hb_total >= 5) ? PetStateOverloaded : PetStateBusy;
    }
    if(app->denial_streak >= GRUMPY_STREAK) return PetStateGrumpy;
    if(app->approval_streak >= HAPPY_STREAK) return PetStateHappy;
    if(app->play_level >= PLAY_HIGH && app->feed_level >= FEED_HIGH) return PetStateContent;
    if(app->feed_level >= FEED_HIGH && app->play_level < PLAY_LOW) return PetStateFocused;
    if(app->play_level < PLAY_LOW && app->feed_level < FEED_LOW &&
       app->lonely_since_ms && now - app->lonely_since_ms > LONELY_SUSTAIN_MS) {
        return PetStateLonely;
    }
    return (app->hb_total > 0) ? PetStateIdle : PetStateSleep;
}

static void set_transient(ClaudeBuddyApp* app, PetState s, uint32_t linger_ms) {
    app->transient_state = s;
    app->transient_until_ms = furi_get_tick() + linger_ms;
}

/* =======================================================================
 *  Claudegotchi classification + decay
 * ======================================================================= */

static void clamp_level(uint32_t* lvl) {
    if(*lvl > LEVEL_MAX) *lvl = LEVEL_MAX;
}

/* Classify the pending msg change: feed if tokens grew during the
 * window, play if not. Clears the pending slot. Also bumps age, and
 * fires the Celebrate transient at milestone ages (10, 50, 200, 1000). */
static void gotchi_classify_pending(ClaudeBuddyApp* app) {
    if(!app->pending_msg_ts) return;
    int tokens_delta = app->hb_tokens - app->pending_start_tokens;
    uint32_t credit = app->pending_msg_bytes;
    if(credit > MSG_CLASSIFY_CAP) credit = MSG_CLASSIFY_CAP;
    if(tokens_delta > 0) {
        app->feed_level += credit;
        clamp_level(&app->feed_level);
    } else {
        app->play_level += credit;
        clamp_level(&app->play_level);
    }
    app->pending_msg_ts = 0;
    app->pending_msg_bytes = 0;

    /* Age bump. Each classified interaction is one life experience.
     * Milestone celebrate fires at each evolution boundary — the
     * transition is already visible (new sprite set), the
     * double-length Celebrate adds a bit of fanfare. */
    uint32_t age = ++app->age_transactions;
    if(age == 10u || age == 100u || age == 1000u || age == 3000u) {
        set_transient(app, PetStateCelebrate, CELEBRATE_LINGER_MS * 2u);
    }
}

/* =======================================================================
 *  Persistence — /ext/apps_data/claude_buddy/state.bin
 * ======================================================================= */

/* Konami-code sequence for hard reset. Up Up Down Down Left Right Left
 * Right — classic minus the B A Start (Flipper d-pad has no B/A). */
static const InputKey KONAMI_CODE[] = {
    InputKeyUp, InputKeyUp, InputKeyDown, InputKeyDown,
    InputKeyLeft, InputKeyRight, InputKeyLeft, InputKeyRight,
};
#define KONAMI_LEN (sizeof(KONAMI_CODE) / sizeof(KONAMI_CODE[0]))

/* Zero all persistable stats back to a fresh-pet state. Must hold mtx.
 *
 * Deliberately does NOT perform I/O (persist_save), notification
 * sequences, or ensure_anim here. An earlier version called all three
 * inline; that froze the device — notification_message on
 * sequence_double_vibro blocks ~400 ms while the buzzer plays,
 * storage_file_open on SD can take 50-200 ms, and icon_animation_start
 * touches the FreeRTOS timer-service queue. All three under the same
 * mutex held by the input task racing against the draw/BT/RX paths was
 * enough to stall everything.
 *
 * The caller flushes to SD and fires notifications AFTER releasing
 * mtx. The next draw tick (≤ 250 ms) re-runs ensure_anim with the
 * freshly-zeroed age, which naturally swaps in the egg sprite. */
static void claudegotchi_reset(ClaudeBuddyApp* app) {
    app->play_level = 0;
    app->feed_level = 0;
    app->age_transactions = 0;
    app->total_approvals = 0;
    app->total_denials = 0;
    app->interaction_bytes = 0;
    app->approval_streak = 0;
    app->denial_streak = 0;
    app->pending_msg_ts = 0;
    app->pending_msg_bytes = 0;
    app->pending_start_tokens = 0;
    app->last_activity_ms = 0;
    app->lonely_since_ms = 0;
    app->starving_since_ms = 0;
    app->last_decay_ms = 0;
    app->tokens_baseline_set = false;
    app->last_celebrated_tokens = 0;
    app->transient_state = PetStateSleep;
    app->transient_until_ms = 0;
    app->konami_progress = 0;
    /* Clear msg so the bars/age panel renders on the next draw —
     * otherwise a sticky status label ("RUN yarn" etc) would hide the
     * reset confirmation until the desktop sends a new heartbeat. */
    app->hb_msg[0] = '\0';
}

static void persist_save(ClaudeBuddyApp* app) {
    Storage* storage = furi_record_open(RECORD_STORAGE);
    storage_simply_mkdir(storage, CB_STATE_DIR);

    ClaudeBuddyPersist state = {
        .magic = CB_STATE_MAGIC,
        .version = CB_STATE_VERSION,
        .play_level = app->play_level,
        .feed_level = app->feed_level,
        .age_transactions = app->age_transactions,
        .total_approvals = app->total_approvals,
        .total_denials = app->total_denials,
        .interaction_bytes = app->interaction_bytes,
        .last_saved_ms = furi_get_tick(),
    };
    memset(state.reserved, 0, sizeof(state.reserved));

    File* f = storage_file_alloc(storage);
    if(storage_file_open(f, CB_STATE_PATH, FSAM_WRITE, FSOM_CREATE_ALWAYS)) {
        storage_file_write(f, &state, sizeof(state));
        storage_file_close(f);
    }
    storage_file_free(f);
    furi_record_close(RECORD_STORAGE);

    app->last_save_ms = furi_get_tick();
}

static void persist_load(ClaudeBuddyApp* app) {
    Storage* storage = furi_record_open(RECORD_STORAGE);
    File* f = storage_file_alloc(storage);
    if(storage_file_open(f, CB_STATE_PATH, FSAM_READ, FSOM_OPEN_EXISTING)) {
        ClaudeBuddyPersist state;
        size_t n = storage_file_read(f, &state, sizeof(state));
        storage_file_close(f);
        if(n == sizeof(state) && state.magic == CB_STATE_MAGIC &&
           state.version == CB_STATE_VERSION) {
            app->play_level = state.play_level;
            app->feed_level = state.feed_level;
            app->age_transactions = state.age_transactions;
            app->total_approvals = state.total_approvals;
            app->total_denials = state.total_denials;
            app->interaction_bytes = state.interaction_bytes;
        }
        /* else: stale magic/version → keep zeros (fresh pet). */
    }
    storage_file_free(f);
    furi_record_close(RECORD_STORAGE);
}

/* Called when an unrecognized msg arrives. First resolves any prior
 * pending entry that's older than CLASSIFY_WINDOW_MS — otherwise we'd
 * lose classification of that earlier entry. Then stamps the new one. */
static void gotchi_record_msg_change(ClaudeBuddyApp* app, uint32_t bytes) {
    uint32_t now = furi_get_tick();
    if(app->pending_msg_ts && now - app->pending_msg_ts > CLASSIFY_WINDOW_MS) {
        gotchi_classify_pending(app);
    } else if(app->pending_msg_ts) {
        /* New input overrides old within window — treat the old one
         * as "ambiguous" and classify based on tokens so far. */
        gotchi_classify_pending(app);
    }
    app->pending_msg_ts = now;
    app->pending_msg_bytes = bytes;
    app->pending_start_tokens = app->hb_tokens;
}

/* Periodic tick — expires pending past window, runs decay, tracks
 * lonely/starving sustain timers. Call under app->mtx. */
static void gotchi_tick(ClaudeBuddyApp* app) {
    uint32_t now = furi_get_tick();

    /* Expire pending beyond the window. */
    if(app->pending_msg_ts && now - app->pending_msg_ts > CLASSIFY_WINDOW_MS) {
        gotchi_classify_pending(app);
    }

    /* Decay once per minute. */
    if(!app->last_decay_ms) {
        app->last_decay_ms = now;
    } else if(now - app->last_decay_ms >= DECAY_TICK_MS) {
        app->play_level = (app->play_level > PLAY_DECAY_PER_MIN) ?
                              app->play_level - PLAY_DECAY_PER_MIN : 0;
        app->feed_level = (app->feed_level > FEED_DECAY_PER_MIN) ?
                              app->feed_level - FEED_DECAY_PER_MIN : 0;
        app->last_decay_ms = now;
    }

    /* Sustain timers. */
    bool low_low = app->play_level < PLAY_LOW && app->feed_level < FEED_LOW;
    if(low_low) {
        if(!app->lonely_since_ms) app->lonely_since_ms = now;
    } else {
        app->lonely_since_ms = 0;
    }

    if(app->feed_level == 0) {
        if(!app->starving_since_ms) app->starving_since_ms = now;
    } else {
        app->starving_since_ms = 0;
    }

    /* Autosave — every 5 min while running. Storage I/O is synchronous
     * from this timer-service task context; for 60 bytes it's fast
     * enough not to cause visible hitches. */
    if(!app->last_save_ms || now - app->last_save_ms >= AUTOSAVE_INTERVAL_MS) {
        persist_save(app);
    }
}

/* Stage-keyed dispatch table: [evo stage][pet state] → Icon*. Loaded
 * in ensure_anim when the derived (stage, state) pair changes. */
#define ICONS_FOR_STAGE(stage) { \
    [PetStateSleep]        = &A_mascot_##stage##_sleep_64x64, \
    [PetStateIdle]         = &A_mascot_##stage##_idle_64x64, \
    [PetStateBusy]         = &A_mascot_##stage##_busy_64x64, \
    [PetStateOverloaded]   = &A_mascot_##stage##_overloaded_64x64, \
    [PetStateAttention]    = &A_mascot_##stage##_attention_64x64, \
    [PetStateHeart]        = &A_mascot_##stage##_heart_64x64, \
    [PetStateCelebrate]    = &A_mascot_##stage##_celebrate_64x64, \
    [PetStateReconnecting] = &A_mascot_##stage##_reconnecting_64x64, \
    [PetStateHappy]        = &A_mascot_##stage##_happy_64x64, \
    [PetStateGrumpy]       = &A_mascot_##stage##_grumpy_64x64, \
    [PetStateContent]      = &A_mascot_##stage##_content_64x64, \
    [PetStateFocused]      = &A_mascot_##stage##_focused_64x64, \
    [PetStateLonely]       = &A_mascot_##stage##_lonely_64x64, \
    [PetStateStarving]     = &A_mascot_##stage##_starving_64x64, \
}

static const Icon* const mascot_icons[EvoCount][PetStateCount] = {
    [EvoEgg]   = ICONS_FOR_STAGE(egg),
    [EvoChild] = ICONS_FOR_STAGE(child),
    [EvoTeen]  = ICONS_FOR_STAGE(teen),
    [EvoAdult] = ICONS_FOR_STAGE(adult),
    [EvoElder] = ICONS_FOR_STAGE(elder),
};
#undef ICONS_FOR_STAGE

/* Evolution thresholds calibrated for ~100 Claude Code messages/day:
 *   Egg → Child    after ~10 interactions (first hour of use)
 *   Child → Teen   after ~100 (first day)
 *   Teen → Adult   after ~1,000 (first ~10 days)
 *   Adult → Elder  after ~3,000 (first month)
 * Milestone celebrates fire on each transition. */
static PetEvoStage evo_stage_from_age(uint32_t age) {
    if(age >= 3000u) return EvoElder;
    if(age >= 1000u) return EvoAdult;
    if(age >= 100u) return EvoTeen;
    if(age >= 10u) return EvoChild;
    return EvoEgg;
}

/* 32×32 attention sprite per evo stage — used only in the Pokemon
 * modal's pet slot. Static icons (not IconAnimation) because the
 * modal always shows a single pose; no animation loop needed.
 * Subsampled from the corresponding 64×64 attention frame. */
static const Icon* attn_32_for_stage(PetEvoStage e) {
    switch(e) {
    case EvoEgg:   return &I_mascot_egg_attn_32x32;
    case EvoChild: return &I_mascot_child_attn_32x32;
    case EvoTeen:  return &I_mascot_teen_attn_32x32;
    case EvoAdult: return &I_mascot_adult_attn_32x32;
    case EvoElder: return &I_mascot_elder_attn_32x32;
    default:       return &I_mascot_child_attn_32x32;
    }
}

static const Icon* anim_icon_for_state(PetState s, PetEvoStage e) {
    if((unsigned)s >= PetStateCount || (unsigned)e >= EvoCount) {
        return &A_mascot_child_idle_64x64;
    }
    const Icon* i = mascot_icons[e][s];
    return i ? i : &A_mascot_child_idle_64x64;
}

/* IconAnimation's internal timer fires this callback on each frame
 * advance. We tell the GUI to redraw, which pulls the new frame via
 * canvas_draw_icon_animation in the draw callback. Runs on the Timer
 * Service task — view_port_update is thread-safe. */
static void anim_update_cb(IconAnimation* instance, void* ctx) {
    UNUSED(instance);
    ClaudeBuddyApp* app = ctx;
    view_port_update(app->view_port);
}

/* Swap to the animation for the given (state, stage) pair if it's
 * not already active. Must be called with app->mtx held. Swaps fire
 * when either axis changes — pet state OR life stage transition.
 *
 * Also detects FORWARD life-stage transitions (Egg→Child→Teen→...)
 * and kicks off the full-screen evolution cinematic. Backward moves
 * (e.g. Konami reset from Teen to Egg) deliberately don't trigger —
 * reset shouldn't celebrate regression. The evolve anim is allocated
 * here; the draw callback renders it full-screen and tears it down
 * when EVOLUTION_LINGER_MS expires. */
static void ensure_anim(ClaudeBuddyApp* app, PetState s) {
    PetEvoStage stage = evo_stage_from_age(app->age_transactions);

    /* Forward stage transition → fire evolution cinematic. Guarded
     * by anim_initialized so the first ensure_anim call after
     * startup / persist_load doesn't trigger on whatever stage the
     * saved age restored to. */
    if(app->anim_initialized && stage > app->anim_stage && !app->evolve_anim) {
        app->evolve_anim = icon_animation_alloc(&A_mascot_evolution_128x64);
        if(app->evolve_anim) {
            icon_animation_set_update_callback(app->evolve_anim, anim_update_cb, app);
            icon_animation_start(app->evolve_anim);
            app->evolve_until_ms = furi_get_tick() + EVOLUTION_LINGER_MS;
            /* Wake the backlight so the user doesn't miss the
             * cinematic if they've stepped away. Single-message
             * sequence (no delay phases), safe to call with the
             * app mutex held per Flipper's notification service. */
            if(app->notifications) {
                notification_message(
                    app->notifications, &sequence_display_backlight_on);
            }
        }
    }

    if(app->current_anim && app->anim_state == s && app->anim_stage == stage) {
        app->anim_initialized = true;
        return;
    }
    if(app->current_anim) {
        icon_animation_stop(app->current_anim);
        icon_animation_free(app->current_anim);
    }
    app->current_anim = icon_animation_alloc(anim_icon_for_state(s, stage));
    icon_animation_set_update_callback(app->current_anim, anim_update_cb, app);
    icon_animation_start(app->current_anim);
    app->anim_state = s;
    app->anim_stage = stage;
    app->anim_initialized = true;
}

/* Egg-crack progression within EvoEgg. Age < 10 keeps us in the Egg
 * stage; as the pet approaches hatching, cracks grow visible on the
 * shell so the user gets a progressive "something's about to happen"
 * cue rather than a silent jump from pristine-egg to Child sprite at
 * age=10. Returns the crack level 0/1/2:
 *   0 — pristine (age 0..3)
 *   1 — hairline single crack (age 4..6)
 *   2 — branching fork (age 7..9)
 * age >= 10 → out of Egg stage, caller should not be invoking this. */
static uint8_t egg_crack_level(uint32_t age) {
    if(age >= 7u) return 2;
    if(age >= 4u) return 1;
    return 0;
}

/* Paint the current mascot animation, then (only if we're still in
 * EvoEgg) layer the age-dependent crack overlay on top. Crack
 * positions picked so the lines fall on the egg's upper light surface
 * (y=16..23) without crossing the face features (eyes at y=28, mouth
 * at y=40). Caller must hold app->mtx — we only read animation /
 * stage / age fields. */
static void draw_mascot(Canvas* canvas, ClaudeBuddyApp* app) {
    if(!app->current_anim) return;
    canvas_draw_icon_animation(canvas, 0, 0, app->current_anim);
    if(app->anim_stage != EvoEgg) return;
    uint8_t lvl = egg_crack_level(app->age_transactions);
    if(lvl == 2) {
        canvas_draw_icon(canvas, 22, 16, &I_overlay_egg_crack_2_22x8);
    } else if(lvl == 1) {
        canvas_draw_icon(canvas, 24, 17, &I_overlay_egg_crack_1_18x6);
    }
}

/* ============================================================
 *  Heartbeat ingest
 * ============================================================ */

static void handle_rx_line(ClaudeBuddyApp* app, const char* line, size_t line_len) {
    jsmn_parser parser;
    jsmntok_t tokens[MAX_TOKENS];
    jsmn_init(&parser);
    int n = jsmn_parse(&parser, line, line_len, tokens, MAX_TOKENS);
    if(n < 1 || tokens[0].type != JSMN_OBJECT) return;

    furi_mutex_acquire(app->mtx, FuriWaitForever);

    int v;
    if((v = json_find_key(line, tokens, n, "total")) >= 0)
        app->hb_total = json_tok_int(line, &tokens[v]);
    if((v = json_find_key(line, tokens, n, "running")) >= 0)
        app->hb_running = json_tok_int(line, &tokens[v]);
    if((v = json_find_key(line, tokens, n, "waiting")) >= 0)
        app->hb_waiting = json_tok_int(line, &tokens[v]);
    if((v = json_find_key(line, tokens, n, "msg")) >= 0) {
        char prev_msg[sizeof(app->hb_msg)];
        strlcpy(prev_msg, app->hb_msg, sizeof(prev_msg));
        json_tok_strcpy(line, &tokens[v], app->hb_msg, sizeof(app->hb_msg));

        /* Classify the new msg. Unmatched patterns are treated as
         * Claudegotchi substrate: stamp activity, accrue
         * interaction_bytes, and open a pending classification window
         * for the play/feed split. Only count on actual change to
         * avoid double-counting when the desktop re-sends the same
         * msg on its 10s keepalive. */
        if(app->hb_msg[0] && strcmp(prev_msg, app->hb_msg) != 0) {
            ClaudeBuddyMsgSummary probe;
            summarize_msg(app->hb_msg, &probe);
            if(probe.label[0] == '\0') {
                uint32_t bytes = (uint32_t)strlen(app->hb_msg);
                app->last_activity_ms = furi_get_tick();
                app->interaction_bytes += bytes;
                gotchi_record_msg_change(app, bytes);
            }
        }
    }

    /* tokens — drives both the celebrate-at-milestone transient AND
     * feed credit. */
    if((v = json_find_key(line, tokens, n, "tokens")) >= 0) {
        int new_tokens = json_tok_int(line, &tokens[v]);

        /* Feed bump from tokens delta. Only after baseline is set —
         * otherwise the first heartbeat (which reports the session's
         * lifetime total, not a delta) would feed the pet based on
         * everything done before the app launched. Cap per heartbeat
         * so a single giant response doesn't saturate the bar. */
        if(app->tokens_baseline_set && new_tokens > app->hb_tokens) {
            uint32_t delta = (uint32_t)(new_tokens - app->hb_tokens);
            uint32_t gain = delta / FEED_TOKENS_PER_UNIT;
            bool capped = false;
            if(gain > FEED_GAIN_CAP_PER_HB) {
                gain = FEED_GAIN_CAP_PER_HB;
                capped = true;
            }
            app->feed_level += gain;
            clamp_level(&app->feed_level);
            /* Debug log visible via `ufbt cli` — lets us correlate
             * token bursts to feed bar movement without opening the
             * device. Grep for "DBG hb". */
            FURI_LOG_I(
                TAG,
                "DBG hb tok_delta=%lu gain=%lu%s feed=%lu/1000 play=%lu/1000 "
                "age=%lu running=%d waiting=%d",
                (unsigned long)delta,
                (unsigned long)gain,
                capped ? "(cap)" : "",
                (unsigned long)app->feed_level,
                (unsigned long)app->play_level,
                (unsigned long)app->age_transactions,
                app->hb_running,
                app->hb_waiting);
        }

        if(!app->tokens_baseline_set && new_tokens > 0) {
            /* First sighting — snap milestone so we don't fire
             * immediately for pre-existing tokens at app start. */
            app->last_celebrated_tokens =
                (new_tokens / TOKENS_MILESTONE) * TOKENS_MILESTONE;
            app->tokens_baseline_set = true;
        } else if(
            app->tokens_baseline_set &&
            new_tokens >= app->last_celebrated_tokens + (int)TOKENS_MILESTONE) {
            set_transient(app, PetStateCelebrate, CELEBRATE_LINGER_MS);
            app->last_celebrated_tokens =
                (new_tokens / TOKENS_MILESTONE) * TOKENS_MILESTONE;
        }
        app->hb_tokens = new_tokens;
    }

    ClaudeBuddyMode prev_mode = app->mode;
    int p_idx = json_find_key(line, tokens, n, "prompt");
    if(p_idx >= 0 && tokens[p_idx].type == JSMN_OBJECT) {
        if((v = json_find_key(line, tokens, n, "id")) >= 0)
            json_tok_strcpy(line, &tokens[v], app->prompt_id, sizeof(app->prompt_id));
        if((v = json_find_key(line, tokens, n, "tool")) >= 0)
            json_tok_strcpy(line, &tokens[v], app->prompt_tool, sizeof(app->prompt_tool));
        if((v = json_find_key(line, tokens, n, "hint")) >= 0)
            json_tok_strcpy(line, &tokens[v], app->prompt_hint, sizeof(app->prompt_hint));
        app->mode = ClaudeBuddyModePrompt;
    } else {
        /* Desktop cleared the prompt — drop the modal. */
        app->mode = ClaudeBuddyModeNormal;
    }
    bool entering_prompt = (prev_mode != ClaudeBuddyModePrompt) &&
                           (app->mode == ClaudeBuddyModePrompt);
    if(entering_prompt) {
        /* Stamp the time so the input handler can detect fast approval. */
        app->prompt_shown_at_ms = furi_get_tick();
        /* Reset cursor to ONCE (left cell) — safe default. A previous
         * DENY selection shouldn't persist into the next prompt and
         * risk an accidental reject on quick OK. */
        app->prompt_cursor_col = 0;
    }

    ensure_anim(app, pet_state_derive(app));

    furi_mutex_release(app->mtx);

    /* On the Normal → Prompt edge: buzz to grab attention, AND kick the
     * display backlight back on if it's gone to sleep — otherwise the
     * user might miss the modal entirely if they walked away. Don't
     * re-fire on subsequent heartbeats while already in the modal. */
    if(entering_prompt && app->notifications) {
        notification_message(app->notifications, &sequence_single_vibro);
        notification_message(app->notifications, &sequence_display_backlight_on);
    }

    view_port_update(app->view_port);
}

/* ============================================================
 *  RX drain thread
 * ============================================================ */

static int32_t claude_buddy_rx_thread(void* ctx) {
    ClaudeBuddyApp* app = ctx;
    uint8_t chunk[64];
    while(app->running) {
        size_t n =
            furi_stream_buffer_receive(app->rx_stream, chunk, sizeof(chunk), 250);
        for(size_t i = 0; i < n; i++) {
            if(app->line_len < LINE_BUF_SIZE - 1) {
                app->line_buf[app->line_len++] = chunk[i];
            } else {
                /* Over-long line — reset and drop until the next newline. */
                app->line_len = 0;
            }
            if(chunk[i] == '\n') {
                handle_rx_line(app, (const char*)app->line_buf, app->line_len);
                app->line_len = 0;
            }
        }
    }
    return 0;
}

/* ============================================================
 *  Drawing
 * ============================================================ */

static void claude_buddy_draw(Canvas* canvas, void* ctx) {
    ClaudeBuddyApp* app = ctx;

    /* Hold the mutex for the whole draw. We need current_anim to stay
     * valid while canvas_draw_icon_animation reads its frame data.
     * Swap-anim sites also hold the mutex, so they can't free
     * current_anim under us here. */
    furi_mutex_acquire(app->mtx, FuriWaitForever);

    /* Re-derive state every draw — picks up transient expiry
     * (heart/celebrate/reconnecting fading back) without needing the
     * swap sites to know about the timeout. ensure_anim is a no-op if
     * state didn't change, so cost is just the derive + a comparison. */
    ensure_anim(app, pet_state_derive(app));

    ClaudeBuddyMode mode = app->mode;
    BtStatus bt_status = app->bt_status;
    bool cccd = app->cccd_enabled;
    int t = app->hb_total, r = app->hb_running, w = app->hb_waiting;

    canvas_clear(canvas);

    /* Evolution cinematic takes over the whole canvas when a stage
     * transition is in flight. Runs for EVOLUTION_LINGER_MS, then
     * tears down the animation and falls through to normal
     * rendering (which now shows the NEW stage sprite). Modal
     * prompts that arrive during the cinematic queue implicitly —
     * the prompt state is set in heartbeat parsing, and the next
     * draw after the cinematic ends will flip into prompt mode. */
    if(app->evolve_anim) {
        uint32_t now = furi_get_tick();
        if(now < app->evolve_until_ms) {
            canvas_draw_icon_animation(canvas, 0, 0, app->evolve_anim);
            furi_mutex_release(app->mtx);
            return;
        }
        /* Expired — teardown so normal rendering resumes next. */
        icon_animation_stop(app->evolve_anim);
        icon_animation_free(app->evolve_anim);
        app->evolve_anim = NULL;
        app->evolve_until_ms = 0;
    }

    uint32_t now_ms = furi_get_tick();
    bool in_narration = app->narration_until_ms > now_ms;

    if(mode == ClaudeBuddyModePrompt || in_narration) {
        /* Pokemon-style battle modal:
         *   y=0..10   banner    "Wild <tool> appeared!"
         *   y=11      divider
         *   y=12..46  combat    "?" glyph (left) + 32×32 pet (right)
         *   y=47      divider
         *   y=48..63  actions   1-row × 2-col grid OR narration text
         *
         * Only ONCE + DENY are rendered because REFERENCE.md lists
         * only those as valid decisions. Left/Right moves cursor,
         * OK confirms. Up/Down have no effect (single-row). After
         * OK, narration replaces the action row for NARRATION_LINGER_MS
         * before the modal closes. */

        /* Banner */
        canvas_set_font(canvas, FontSecondary);
        char banner[56]; /* "Wild " + up to 32-char tool + " appeared!" + null */
        snprintf(banner, sizeof(banner), "Wild %s appeared!", app->prompt_tool);
        canvas_draw_str(canvas, 2, 9, banner);
        canvas_draw_line(canvas, 0, 11, 127, 11);

        /* Combat zone — tool glyph (left) + attention pet (right).
         * Tool glyph is the generic framed "?"; tool NAME sits in
         * the banner above, so the left slot stays stage-agnostic. */
        canvas_draw_icon(canvas, 16, 14, &I_icon_tool_32x32);
        canvas_draw_icon(canvas, 80, 14, attn_32_for_stage(app->anim_stage));

        canvas_draw_line(canvas, 0, 47, 127, 47);

        if(in_narration) {
            /* Narration replaces the grid: "Claudochi used X!" in two
             * lines because "APPROVE!"/"DENY!" in FontPrimary takes
             * enough horizontal space that a one-line "Claudochi used
             * DENY!" overruns 128 px. */
            canvas_set_font(canvas, FontSecondary);
            canvas_draw_str(canvas, 16, 55, "Claudochi used");
            canvas_set_font(canvas, FontPrimary);
            const char* used = "???";
            if(strcmp(app->narration_decision, "once") == 0) used = "APPROVE!";
            else if(strcmp(app->narration_decision, "deny") == 0) used = "DENY!";
            canvas_draw_str(canvas, 40, 63, used);
        } else {
            /* Action row — ONCE | DENY with vertical divider + cursor. */
            canvas_draw_line(canvas, 63, 48, 63, 63);
            canvas_set_font(canvas, FontSecondary);
            static const char* const LABELS[2] = {"ONCE", "DENY"};
            const int cell_xs[2] = {2, 66};
            const int label_xs[2] = {10, 74};
            const int by = 60;
            for(int c = 0; c < 2; c++) {
                if(c == app->prompt_cursor_col) {
                    canvas_draw_str(canvas, cell_xs[c], by, ">");
                }
                canvas_draw_str(canvas, label_xs[c], by, LABELS[c]);
            }
        }

        furi_mutex_release(app->mtx);
        return;
    }

    /* Normal mode: mascot carries the state signal (state-driven frames
     * cover sleep/idle/busy/attention, plus blue LED for connected).
     * Right column is deliberately minimal: just a title block and the
     * current msg. Removed BT status line + T/R/W counters — they
     * duplicated info the mascot already conveys, and the msg has
     * more room to breathe now. */
    (void)bt_status;
    (void)cccd;
    (void)t;
    (void)r;
    (void)w;

    draw_mascot(canvas, app);

    /* Title "Claudochi" in FontPrimary — Tamagotchi-ified brand mark.
     * Flipper's default fonts are ASCII-only (haxrcorp_4089_tr,
     * helvB08_tr), so Japanese くろどっち can't render without a custom
     * font; romanized "Claudochi" carries the same tamagotchi flavor
     * and fits the 62 px column where "Claudebuddy" clipped. */
    canvas_set_font(canvas, FontPrimary);
    canvas_draw_str(canvas, 66, 12, "Claudochi");

    /* Summarized msg: only recognized status patterns render. Free-form
     * text (including what the user is typing into Claude Code) is
     * deliberately NOT shown — bare user input on a pocket-sized screen
     * is a privacy leak. When an unrecognized msg recently arrived,
     * show a pulsing "…" instead to acknowledge "something's happening"
     * without surfacing the content. */
    ClaudeBuddyMsgSummary sum;
    summarize_msg(app->hb_msg, &sum);
    if(sum.label[0]) {
        canvas_set_font(canvas, FontPrimary);
        canvas_draw_str(canvas, 66, 36, sum.label);
        if(sum.detail[0]) {
            canvas_set_font(canvas, FontSecondary);
            canvas_draw_str(canvas, 66, 50, sum.detail);
        }
    } else {
        /* No known label → Claudegotchi panel, two-row per stat:
         *   row A: [10x10 glyph] Label text
         *   row B: gauge bar full-width
         * Stacked for Happy then Food, with Age on the last row.
         * Bars fill positively (high = good). */
        const int bx = 66, bw = 60, bh = 5;

        canvas_draw_icon(canvas, 66, 13, &I_icon_heart_10x10);
        canvas_set_font(canvas, FontSecondary);
        canvas_draw_str(canvas, 80, 22, "Happy");
        canvas_draw_frame(canvas, bx, 25, bw, bh);
        uint32_t pfill = (app->play_level * (bw - 2)) / LEVEL_MAX;
        if(pfill > 0) canvas_draw_box(canvas, bx + 1, 26, (int)pfill, bh - 2);

        canvas_draw_icon(canvas, 66, 33, &I_icon_burger_10x10);
        canvas_draw_str(canvas, 80, 42, "Food");
        canvas_draw_frame(canvas, bx, 45, bw, bh);
        uint32_t ffill = (app->feed_level * (bw - 2)) / LEVEL_MAX;
        if(ffill > 0) canvas_draw_box(canvas, bx + 1, 46, (int)ffill, bh - 2);

        /* Age readout on the last row + typing dots inline. */
        uint32_t now = furi_get_tick();
        bool typing = app->last_activity_ms && now - app->last_activity_ms < 2000u;
        char age_line[20];
        snprintf(
            age_line,
            sizeof(age_line),
            typing ? "Age:%lu ..." : "Age:%lu",
            (unsigned long)app->age_transactions);
        canvas_draw_str(canvas, 66, 60, age_line);
    }

    /* Power overlays: upper-right 8x8 corner.
     *   - Charging (USB plugged in): lightning bolt
     *   - Low battery (<20%): battery warning icon
     * Charging takes priority over low — if both (e.g. starting to
     * charge at 10%), user sees the "it's being fed" glyph first. */
    if(furi_hal_power_is_charging()) {
        canvas_draw_icon(canvas, 120, 0, &I_overlay_charging_8x8);
    } else if(furi_hal_power_get_pct() < LOW_BATTERY_PCT) {
        canvas_draw_icon(canvas, 120, 0, &I_overlay_hungry_8x8);
    }

    furi_mutex_release(app->mtx);
}

/* ============================================================
 *  Input + BT callbacks
 * ============================================================ */

static void claude_buddy_input(InputEvent* event, void* ctx) {
    ClaudeBuddyApp* app = ctx;
    furi_message_queue_put(app->input_queue, event, FuriWaitForever);
}

static void claude_buddy_redraw_tick(void* ctx) {
    ClaudeBuddyApp* app = ctx;
    /* Tamagotchi tick: decay, expire pending classifications, track
     * lonely/starving sustain timers. Runs at 4 Hz (REDRAW_PERIOD_MS)
     * so lonely/starving transitions are picked up within ~250ms. */
    furi_mutex_acquire(app->mtx, FuriWaitForever);
    gotchi_tick(app);
    furi_mutex_release(app->mtx);
    view_port_update(app->view_port);
}

static void claude_buddy_on_bt_status(BtStatus status, void* ctx) {
    ClaudeBuddyApp* app = ctx;
    furi_mutex_acquire(app->mtx, FuriWaitForever);
    BtStatus prev = app->bt_status;
    app->bt_status = status;

    /* Reconnecting transient: was Connected, now Advertising. */
    if(prev == BtStatusConnected && status == BtStatusAdvertising) {
        set_transient(app, PetStateReconnecting, RECONNECTING_LINGER_MS);
    }
    if(status == BtStatusConnected) {
        app->was_connected = true;
    }

    ensure_anim(app, pet_state_derive(app));
    furi_mutex_release(app->mtx);

    /* Blue LED while a central is connected, off otherwise — mirrors
     * hid_app/hid.c:100. Small quality-of-life indicator that matches
     * stock Flipper UX conventions for BLE apps. */
    if(app->notifications) {
        notification_message(
            app->notifications,
            status == BtStatusConnected ? &sequence_set_blue_255 : &sequence_reset_blue);
    }
}

static void claude_buddy_on_rx(const uint8_t* data, uint16_t len, void* ctx) {
    ClaudeBuddyApp* app = ctx;
    /* BLE thread context — push bytes and return fast. */
    furi_stream_buffer_send(app->rx_stream, data, len, 0);
}

static void claude_buddy_on_conn(bool connected, void* ctx) {
    ClaudeBuddyApp* app = ctx;
    furi_mutex_acquire(app->mtx, FuriWaitForever);
    app->cccd_enabled = connected;
    furi_mutex_release(app->mtx);
}

/* ============================================================
 *  Entry point
 * ============================================================ */

int32_t claude_buddy_app(void* p) {
    UNUSED(p);
    ClaudeBuddyApp* app = malloc(sizeof(ClaudeBuddyApp));
    memset(app, 0, sizeof(*app));

    app->mtx = furi_mutex_alloc(FuriMutexTypeNormal);
    app->input_queue = furi_message_queue_alloc(8, sizeof(InputEvent));
    app->rx_stream = furi_stream_buffer_alloc(RX_STREAM_SIZE, RX_STREAM_TRIGGER);
    app->running = true;
    app->notifications = furi_record_open(RECORD_NOTIFICATION);

    /* Restore persisted Tamagotchi stats before doing anything else —
     * the pet remembers across reboots. */
    persist_load(app);

    /* Start with the sleep animation — we haven't connected to anyone
     * yet and heartbeat hasn't been parsed. Will swap as state evolves. */
    furi_mutex_acquire(app->mtx, FuriWaitForever);
    ensure_anim(app, PetStateSleep);
    furi_mutex_release(app->mtx);

    app->view_port = view_port_alloc();
    view_port_draw_callback_set(app->view_port, claude_buddy_draw, app);
    view_port_input_callback_set(app->view_port, claude_buddy_input, app);
    app->gui = furi_record_open(RECORD_GUI);
    gui_add_view_port(app->gui, app->view_port, GuiLayerFullscreen);
    app->redraw_timer = furi_timer_alloc(claude_buddy_redraw_tick, FuriTimerTypePeriodic, app);
    furi_timer_start(app->redraw_timer, REDRAW_PERIOD_MS);

    /* RX drain thread */
    app->rx_thread = furi_thread_alloc_ex("ClaudeBuddyRx", RX_THREAD_STACK, claude_buddy_rx_thread, app);
    furi_thread_start(app->rx_thread);

    /* Bring up BLE */
    app->bt = furi_record_open(RECORD_BT);
    bt_set_status_changed_callback(app->bt, claude_buddy_on_bt_status, app);
    app->profile = bt_profile_start(app->bt, ble_profile_claude_buddy, NULL);
    if(!app->profile) {
        FURI_LOG_E(TAG, "bt_profile_start failed");
    } else {
        claude_buddy_profile_set_rx_callback(app->profile, claude_buddy_on_rx, app);
        claude_buddy_profile_set_conn_callback(app->profile, claude_buddy_on_conn, app);
    }

    /* Main input loop */
    InputEvent event;
    while(furi_message_queue_get(app->input_queue, &event, FuriWaitForever) == FuriStatusOk) {
        if(event.type != InputTypeShort) continue;

        /* Back always exits, regardless of mode. */
        if(event.key == InputKeyBack) break;

        /* Snapshot mode + prompt id for the handler below. */
        furi_mutex_acquire(app->mtx, FuriWaitForever);
        ClaudeBuddyMode mode = app->mode;
        char id[48];
        strlcpy(id, app->prompt_id, sizeof(id));
        bool narration_active = app->narration_until_ms > furi_get_tick();

        /* Narration phase swallows all input — Pokemon-game feel:
         * text box plays out to completion. Back still exits (handled
         * above this block). */
        if(narration_active) {
            furi_mutex_release(app->mtx);
            continue;
        }

        /* Konami-code reset — Up Up Down Down Left Right Left Right.
         * Only when NOT in a prompt (so Left in prompt mode still
         * means deny, not just konami progress). Running match;
         * any non-matching key that's also not the start resets. */
        bool konami_fired = false;
        if(mode != ClaudeBuddyModePrompt) {
            if(event.key == KONAMI_CODE[app->konami_progress]) {
                app->konami_progress++;
                if(app->konami_progress >= KONAMI_LEN) {
                    claudegotchi_reset(app);
                    konami_fired = true;
                }
            } else {
                app->konami_progress = (event.key == KONAMI_CODE[0]) ? 1 : 0;
            }
        }

        furi_mutex_release(app->mtx);

        /* Reset side-effects fire outside the mutex — see the
         * comment above claudegotchi_reset for why. persist_save
         * touches Storage (can block on SD), double_vibro blocks on
         * the buzzer sequence, and backlight_on kicks the display
         * awake for visual confirmation. All three are safe to call
         * without the app mutex because claudegotchi_reset already
         * settled the in-memory state. */
        if(konami_fired) {
            persist_save(app);
            if(app->notifications) {
                notification_message(app->notifications, &sequence_double_vibro);
                notification_message(app->notifications, &sequence_display_backlight_on);
            }
            view_port_update(app->view_port);
        }

        if(mode != ClaudeBuddyModePrompt) continue;
        if(id[0] == '\0') continue;

        /* Pokemon nav: Left/Right cycle cursor between ONCE (col=0)
         * and DENY (col=1). Up/Down no-op. OK confirms current cell. */
        if(event.key == InputKeyLeft || event.key == InputKeyRight) {
            furi_mutex_acquire(app->mtx, FuriWaitForever);
            if(event.key == InputKeyLeft && app->prompt_cursor_col > 0) {
                app->prompt_cursor_col--;
            } else if(event.key == InputKeyRight && app->prompt_cursor_col < 1) {
                app->prompt_cursor_col++;
            }
            furi_mutex_release(app->mtx);
            view_port_update(app->view_port);
            continue;
        }

        if(event.key != InputKeyOk) continue;

        /* OK confirms — decision from current cursor column. */
        furi_mutex_acquire(app->mtx, FuriWaitForever);
        const char* decision =
            (app->prompt_cursor_col == 0) ? "once" : "deny";
        furi_mutex_release(app->mtx);

        bool tx_ok = false;
        if(app->profile) {
            char json[160];
            int n = snprintf(
                json,
                sizeof(json),
                "{\"cmd\":\"permission\",\"id\":\"%s\",\"decision\":\"%s\"}\n",
                id,
                decision);
            if(n > 0 && (size_t)n < sizeof(json)) {
                tx_ok = claude_buddy_profile_tx(
                    app->profile, (const uint8_t*)json, (uint16_t)n);
            }
        }

        /* Dismiss modal locally regardless of TX result — immediate
         * visual ack via the narration phase. Also update streak
         * counters + heart-transient here so the pet's mood
         * reflects the decision immediately.
         *
         * Deliberately do NOT overwrite hb_msg with "sent: X (ok)"
         * — the narration already shows "Claudochi used APPROVE!"
         * and after that expires the home screen should resume its
         * normal bars/age panel rather than holding a stale status
         * line until the next heartbeat. If TX failed, the desktop
         * will re-send the prompt and the modal will naturally
         * reopen after narration expires. */
        furi_mutex_acquire(app->mtx, FuriWaitForever);
        app->mode = ClaudeBuddyModeNormal;
        app->prompt_id[0] = '\0';
        (void)tx_ok;
        /* Kick off the narration phase — modal stays visible showing
         * "Claudochi used X!" for NARRATION_LINGER_MS even though
         * mode already flipped to Normal. Draw path gates on
         * narration_until_ms in addition to mode == Prompt. */
        uint32_t now = furi_get_tick();
        strlcpy(app->narration_decision, decision, sizeof(app->narration_decision));
        app->narration_until_ms = now + NARRATION_LINGER_MS;

        /* Approval = anything but deny. Derived from the decision
         * string because OK now confirms whichever cell the cursor
         * is on, not just ONCE. */
        bool approved = strcmp(decision, "deny") != 0;
        if(approved) {
            app->approval_streak++;
            app->denial_streak = 0;
            app->total_approvals++;
            /* Approval feeds the pet — explicit intent to run the
             * tool = food. Separate from tokens-delta feed so the
             * user sees immediate response to their decision,
             * independent of how big the resulting tool run is. */
            app->feed_level += FEED_PER_APPROVAL;
            clamp_level(&app->feed_level);
            /* Heart if approval happened within 5s of the prompt arriving. */
            if(app->prompt_shown_at_ms &&
               now - app->prompt_shown_at_ms < HEART_TRIGGER_MS) {
                set_transient(app, PetStateHeart, HEART_LINGER_MS);
            }
        } else {
            app->denial_streak++;
            app->approval_streak = 0;
            app->total_denials++;
        }

        ensure_anim(app, pet_state_derive(app));
        furi_mutex_release(app->mtx);
        view_port_update(app->view_port);
    }

    /* Teardown: stop drain thread, then tear down BLE, then GUI. */
    app->running = false;
    furi_thread_join(app->rx_thread);
    furi_thread_free(app->rx_thread);

    /* Flush Tamagotchi stats to SD before losing anything else. */
    persist_save(app);

    if(app->profile) {
        bt_profile_restore_default(app->bt);
    }
    bt_set_status_changed_callback(app->bt, NULL, NULL);
    furi_record_close(RECORD_BT);

    /* Make sure the LED is off when we leave. */
    notification_message(app->notifications, &sequence_reset_blue);
    furi_record_close(RECORD_NOTIFICATION);

    furi_timer_stop(app->redraw_timer);
    furi_timer_free(app->redraw_timer);
    gui_remove_view_port(app->gui, app->view_port);
    view_port_free(app->view_port);
    furi_record_close(RECORD_GUI);

    /* Animation after view_port — the icon-animation timer could have
     * fired a view_port_update between our gui_remove_view_port and
     * view_port_free. Stopping the animation first avoids that race. */
    if(app->current_anim) {
        icon_animation_stop(app->current_anim);
        icon_animation_free(app->current_anim);
    }
    /* Evolution cinematic may still be in flight on teardown (user
     * hit Back mid-animation). Same timer-service race applies. */
    if(app->evolve_anim) {
        icon_animation_stop(app->evolve_anim);
        icon_animation_free(app->evolve_anim);
    }

    furi_stream_buffer_free(app->rx_stream);
    furi_message_queue_free(app->input_queue);
    furi_mutex_free(app->mtx);
    free(app);
    return 0;
}
