/* Phase 3: heartbeat JSON rendering + permission-prompt modal.
 *
 * Architecture:
 *   - BLE RX callback (BLE thread) pushes raw bytes into a FuriStreamBuffer.
 *   - A dedicated drain thread accumulates bytes into a line buffer, parses
 *     one JSON object per '\n' with jsmn, and updates shared app state
 *     under a mutex.
 *   - The main thread drives the GUI: a redraw timer at 4 Hz polls state
 *     and repaints, and an input queue handles button events.
 *   - When the parsed heartbeat contains a `prompt` object, the app enters
 *     ModePrompt and renders a modal with tool/hint + keybindings. OK and
 *     Left send the permission response back via TX; the desktop clears
 *     the prompt from subsequent heartbeats, which drops us back to
 *     ModeNormal.
 */

#include "claude_buddy_profile.h"

#include <furi.h>
#include <furi_hal_version.h>
#include <bt/bt_service/bt.h>
#include <gui/gui.h>
#include <gui/view_port.h>
#include <input/input.h>
#include <notification/notification_messages.h>
#include <gui/icon_animation.h>
#include <furi_hal_power.h>
#include <storage/storage.h>

/* Generated by the build from PNGs under claude_buddy/assets/ — exposes
 * the compiled Icon symbols. Animated subdirs (with a frame_rate file)
 * produce A_* Icons; each is wrapped in an IconAnimation at runtime. */
#include "claude_buddy_icons.h"

#define JSMN_STATIC
#include "jsmn.h"

#include <stdlib.h>
#include <string.h>

#define TAG "ClaudeBuddyApp"

#define REDRAW_PERIOD_MS    250
#define LINE_BUF_SIZE       1024
#define RX_STREAM_SIZE      2048
#define RX_STREAM_TRIGGER   1
#define RX_THREAD_STACK     2048
#define MAX_TOKENS          64

typedef enum {
    ClaudeBuddyModeNormal,
    ClaudeBuddyModePrompt,
} ClaudeBuddyMode;

/* Visible pet state. Derived from BT state + heartbeat counts + local
 * tracking (streaks, transients, battery, tamagotchi stats). Priority
 * order (top wins) in pet_state_derive() below. */
typedef enum {
    PetStateSleep,        /* disconnected, or nothing open on desktop */
    PetStateIdle,         /* connected, sessions open but not generating */
    PetStateBusy,         /* running > 0 */
    PetStateOverloaded,   /* running > 0 && total >= 5 */
    PetStateAttention,    /* waiting > 0 or modal open */
    PetStateHeart,        /* transient: approved within 5s of prompt */
    PetStateCelebrate,    /* transient: tokens crossed 10k milestone */
    PetStateReconnecting, /* transient: was Connected, now Advertising */
    PetStateHappy,        /* 3+ consecutive approvals (mood) */
    PetStateGrumpy,       /* 2+ consecutive denials (mood) */
    /* Tamagotchi-layer moods (Phase 5e): play/feed stats drive these.
     * Longer horizon than approval streaks — persist across prompt
     * decisions, decay over minutes. */
    PetStateContent,      /* play+feed both high */
    PetStateFocused,      /* feed high, play low — quietly at work */
    PetStateLonely,       /* both low, sustained */
    PetStateStarving,     /* feed == 0 for extended period */
    PetStateCount,
} PetState;

/* Life stages. age_transactions drives which sprite set we use for
 * a given PetState (Phase 5g evolution). */
typedef enum {
    EvoEgg = 0,   /* ages 0..9, no limbs, peek-a-boo through crack */
    EvoChild,     /* ages 10..49, current baseline boxy mascot */
    EvoTeen,      /* ages 50..199, taller with hair tuft */
    EvoAdult,     /* ages 200..999, fuller with belt detail */
    EvoElder,     /* ages 1000+, wizard hat + evolved form */
    EvoCount,
} PetEvoStage;

#define TOKENS_MILESTONE         (10000u)
#define HEART_TRIGGER_MS         (5000u)
#define HEART_LINGER_MS          (5000u)
#define CELEBRATE_LINGER_MS      (5000u)
#define RECONNECTING_LINGER_MS   (8000u)
#define HAPPY_STREAK             (3)
#define GRUMPY_STREAK            (2)
#define LOW_BATTERY_PCT          (20)

/* Tamagotchi tuning */
#define LEVEL_MAX                (1000u)
#define PLAY_HIGH                (500u)
#define PLAY_LOW                 (200u)
#define FEED_HIGH                (500u)
#define FEED_LOW                 (200u)
#define CLASSIFY_WINDOW_MS       (30000u)  /* msg → tool-call window */
#define DECAY_TICK_MS            (60000u)  /* decay once per minute */
#define PLAY_DECAY_PER_MIN       (2u)
#define FEED_DECAY_PER_MIN       (1u)
#define LONELY_SUSTAIN_MS        (90000u)  /* 90s of low-low = lonely */
#define STARVING_SUSTAIN_MS      (300000u) /* 5min of zero feed = starving */
#define AUTOSAVE_INTERVAL_MS     (300000u) /* save every 5 min */

/* Persistence — state survives across app restarts. */
#define CB_STATE_MAGIC           (0x43424450u)  /* "CBDP" */
#define CB_STATE_VERSION         (1u)
#define CB_STATE_DIR             "/ext/apps_data/claude_buddy"
#define CB_STATE_PATH            "/ext/apps_data/claude_buddy/state.bin"

typedef struct {
    uint32_t magic;
    uint32_t version;
    uint32_t play_level;
    uint32_t feed_level;
    uint32_t age_transactions;
    uint32_t total_approvals;
    uint32_t total_denials;
    uint32_t interaction_bytes;
    uint32_t last_saved_ms;
    uint32_t reserved[6];
} ClaudeBuddyPersist;

typedef struct {
    FuriMutex* mtx;

    /* BT status */
    BtStatus bt_status;
    bool cccd_enabled;

    /* Parsed heartbeat fields */
    int hb_total;
    int hb_running;
    int hb_waiting;
    char hb_msg[64];

    /* Prompt state (valid when mode == Prompt) */
    ClaudeBuddyMode mode;
    char prompt_id[48];
    char prompt_tool[32];
    char prompt_hint[96];

    /* GUI */
    FuriMessageQueue* input_queue;
    ViewPort* view_port;
    Gui* gui;
    FuriTimer* redraw_timer;

    /* RX pipeline */
    FuriStreamBuffer* rx_stream;
    FuriThread* rx_thread;
    volatile bool running;
    uint8_t line_buf[LINE_BUF_SIZE];
    size_t line_len;

    /* BT service + active profile */
    Bt* bt;
    FuriHalBleProfileBase* profile;

    /* LED / haptic */
    NotificationApp* notifications;

    /* Currently-playing mascot animation. Swapped by ensure_anim()
     * when the derived pet state OR life stage changes. Guarded by
     * app->mtx. */
    IconAnimation* current_anim;
    PetState anim_state;
    PetEvoStage anim_stage;

    /* Tokens milestone tracking — celebrate when `tokens` jumps past
     * the next 10k mark. last_celebrated seeded on first heartbeat so
     * we don't celebrate mid-session tokens at app start. */
    int hb_tokens;
    int last_celebrated_tokens;
    bool tokens_baseline_set;

    /* Transient overrides (heart / celebrate / reconnecting).
     * transient_until_ms == 0 means no transient is active. */
    PetState transient_state;
    uint32_t transient_until_ms;
    uint32_t prompt_shown_at_ms; /* reset when a prompt first appears */

    /* Streak counters driven by the prompt input handler. */
    int approval_streak;
    int denial_streak;

    /* Reconnecting detection — fires when we go Connected → Advertising.
     * We deliberately don't reset on subsequent states so repeated
     * reconnects keep triggering. */
    bool was_connected;

    /* Claudegotchi substrate — unrecognized msg arrivals (user typing,
     * narrative text, anything that doesn't match summarize_msg's
     * status ladder) feed into these counters. We don't render the
     * content; just acknowledge the activity with a pulsing "…"
     * indicator and accumulate for the Phase 5e play/feed mechanics. */
    uint32_t last_activity_ms;
    uint32_t interaction_bytes;

    /* Play/feed levels, each 0..LEVEL_MAX. Drive Content/Focused/
     * Lonely/Starving mood states. Phase 5e.1 in-memory only; Phase
     * 5e.2 will persist them to SD. */
    uint32_t play_level;
    uint32_t feed_level;

    /* Pending classification window: when an unrecognized msg arrives,
     * we stamp it here. If tokens grow within CLASSIFY_WINDOW_MS, it's
     * credited to feed (Claude worked on the input). If the window
     * expires without tokens growth, it's credited to play (just
     * chatter). Single-slot; a new msg change while pending exists
     * forces classification of the old one first. */
    uint32_t pending_msg_ts;
    uint32_t pending_msg_bytes;
    int pending_start_tokens;

    /* Sustained-state tracking for Lonely/Starving mood triggers. */
    uint32_t lonely_since_ms;
    uint32_t starving_since_ms;
    uint32_t last_decay_ms;

    /* Lifetime counters, persisted to SD. age_transactions is the pet's
     * "age" — bumps on every classified interaction. total_approvals
     * and total_denials are lifetime button totals; approval_streak /
     * denial_streak above are session-scoped. */
    uint32_t age_transactions;
    uint32_t total_approvals;
    uint32_t total_denials;

    /* Autosave: periodically flush state to SD so an unplanned exit
     * doesn't lose progress. Milestones also trigger an immediate save. */
    uint32_t last_save_ms;
} ClaudeBuddyApp;

/* Forward so callbacks can reference the struct. */
static void ensure_anim(ClaudeBuddyApp* app, PetState s);

/* ============================================================
 *  JSON helpers — small wrappers on jsmn
 * ============================================================ */

static bool tok_streq(const char* json, const jsmntok_t* t, const char* s) {
    int len = t->end - t->start;
    return (int)strlen(s) == len && strncmp(json + t->start, s, len) == 0;
}

/* Linear key search: find the first STRING token matching `key` and
 * return the index of the immediately following (value) token. Good
 * enough for the Hardware Buddy heartbeat since all keys we care about
 * are globally unique across the object (total/running/waiting/msg at
 * top level; id/tool/hint only under `prompt`). Returns -1 if not
 * found. */
static int json_find_key(const char* json, const jsmntok_t* tokens, int n, const char* key) {
    for(int i = 0; i < n - 1; i++) {
        if(tokens[i].type == JSMN_STRING && tok_streq(json, &tokens[i], key)) {
            return i + 1;
        }
    }
    return -1;
}

static int json_tok_int(const char* json, const jsmntok_t* t) {
    char buf[16] = {0};
    int len = t->end - t->start;
    if(len < 0 || len >= (int)sizeof(buf)) return 0;
    memcpy(buf, json + t->start, len);
    return atoi(buf);
}

static void
    json_tok_strcpy(const char* json, const jsmntok_t* t, char* dst, size_t dst_size) {
    int len = t->end - t->start;
    if(len < 0) len = 0;
    if(len >= (int)dst_size) len = dst_size - 1;
    memcpy(dst, json + t->start, len);
    dst[len] = '\0';
}

/* Summarize a free-form heartbeat `msg` string into a short label
 * (≤ 5 chars) plus an optional detail word. The desktop's msg field is
 * "one-line summary suitable for a small display" per REFERENCE.md, but
 * in practice still too long for 64 px of right-column font-secondary.
 * Common observed patterns:
 *     "running: yarn test"      → RUN / yarn
 *     "approve: Bash"           → ASK / Bash
 *     "called bash"             → RUN / bash
 *     "done(success), 1 turns"  → DONE
 *     "done(failure), …"        → FAIL
 *     "approved"                → OK
 *     <anything else>           → raw msg in detail, no label
 * Extend the ladder here as new desktop patterns surface. */
typedef struct {
    char label[8];    /* 1-5 char summary, rendered in FontPrimary */
    char detail[24];  /* optional trailing word(s), FontSecondary */
} ClaudeBuddyMsgSummary;

static void copy_first_word(const char* src, char* dst, size_t dst_size) {
    while(*src == ' ') src++;
    size_t n = 0;
    while(*src && *src != ' ' && n < dst_size - 1) {
        dst[n++] = *src++;
    }
    dst[n] = '\0';
}

static void summarize_msg(const char* raw, ClaudeBuddyMsgSummary* s) {
    s->label[0] = '\0';
    s->detail[0] = '\0';
    if(!raw || !raw[0]) return;

    /* Desktop sometimes wraps msg in parens, e.g. "(called Bash)".
     * Strip a leading "(" so pattern matching works uniformly. */
    const char* p = raw;
    if(*p == '(') p++;

    if(strncmp(p, "running:", 8) == 0) {
        strlcpy(s->label, "RUN", sizeof(s->label));
        copy_first_word(p + 8, s->detail, sizeof(s->detail));
    } else if(strncmp(p, "approve:", 8) == 0) {
        strlcpy(s->label, "ASK", sizeof(s->label));
        copy_first_word(p + 8, s->detail, sizeof(s->detail));
    } else if(strncmp(p, "called ", 7) == 0) {
        strlcpy(s->label, "RUN", sizeof(s->label));
        copy_first_word(p + 7, s->detail, sizeof(s->detail));
    } else if(strncmp(p, "done(success", 12) == 0) {
        strlcpy(s->label, "DONE", sizeof(s->label));
    } else if(
        strncmp(p, "done(failure", 12) == 0 || strncmp(p, "done(error", 10) == 0 ||
        strncmp(p, "failed", 6) == 0) {
        strlcpy(s->label, "FAIL", sizeof(s->label));
    } else if(strcmp(p, "approved") == 0) {
        strlcpy(s->label, "OK", sizeof(s->label));
    } else if(strcmp(p, "denied") == 0) {
        strlcpy(s->label, "NO", sizeof(s->label));
    } else {
        /* Unknown pattern — show the raw text truncated, no label. */
        strlcpy(s->detail, raw, sizeof(s->detail));
    }

    /* Trim a trailing ")" that the paren-wrap leaves behind in detail. */
    size_t n = strlen(s->detail);
    if(n > 0 && s->detail[n - 1] == ')') s->detail[n - 1] = '\0';
}

/* Full pet state derivation — priority order (first match wins):
 *    1. Attention   — prompt pending
 *    2. Transient   — heart / celebrate / reconnecting within linger
 *    3. Starving    — feed == 0 for STARVING_SUSTAIN_MS (critical)
 *    4. Sleep       — BT not connected
 *    5. Overloaded  — running > 0 && total >= 5
 *    6. Busy        — running > 0
 *    7. Grumpy      — denial_streak >= GRUMPY_STREAK  (short-horizon UX)
 *    8. Happy       — approval_streak >= HAPPY_STREAK (short-horizon UX)
 *    9. Content     — play & feed both high           (long-horizon mood)
 *   10. Focused     — feed high, play low             (long-horizon mood)
 *   11. Lonely      — both low for LONELY_SUSTAIN_MS  (long-horizon mood)
 *   12. Idle        — connected with sessions
 *   13. Sleep       — default (no sessions)
 * Caller must hold app->mtx. */
static PetState pet_state_derive(const ClaudeBuddyApp* app) {
    if(app->mode == ClaudeBuddyModePrompt || app->hb_waiting > 0) {
        return PetStateAttention;
    }
    uint32_t now = furi_get_tick();
    if(app->transient_until_ms && now < app->transient_until_ms) {
        return app->transient_state;
    }
    if(app->starving_since_ms && now - app->starving_since_ms > STARVING_SUSTAIN_MS) {
        return PetStateStarving;
    }
    if(app->bt_status != BtStatusConnected) return PetStateSleep;
    if(app->hb_running > 0) {
        return (app->hb_total >= 5) ? PetStateOverloaded : PetStateBusy;
    }
    if(app->denial_streak >= GRUMPY_STREAK) return PetStateGrumpy;
    if(app->approval_streak >= HAPPY_STREAK) return PetStateHappy;
    if(app->play_level >= PLAY_HIGH && app->feed_level >= FEED_HIGH) return PetStateContent;
    if(app->feed_level >= FEED_HIGH && app->play_level < PLAY_LOW) return PetStateFocused;
    if(app->play_level < PLAY_LOW && app->feed_level < FEED_LOW &&
       app->lonely_since_ms && now - app->lonely_since_ms > LONELY_SUSTAIN_MS) {
        return PetStateLonely;
    }
    return (app->hb_total > 0) ? PetStateIdle : PetStateSleep;
}

static void set_transient(ClaudeBuddyApp* app, PetState s, uint32_t linger_ms) {
    app->transient_state = s;
    app->transient_until_ms = furi_get_tick() + linger_ms;
}

/* =======================================================================
 *  Claudegotchi classification + decay
 * ======================================================================= */

static void clamp_level(uint32_t* lvl) {
    if(*lvl > LEVEL_MAX) *lvl = LEVEL_MAX;
}

/* Classify the pending msg change: feed if tokens grew during the
 * window, play if not. Clears the pending slot. Also bumps age, and
 * fires the Celebrate transient at milestone ages (10, 50, 200, 1000). */
static void gotchi_classify_pending(ClaudeBuddyApp* app) {
    if(!app->pending_msg_ts) return;
    int tokens_delta = app->hb_tokens - app->pending_start_tokens;
    if(tokens_delta > 0) {
        app->feed_level += app->pending_msg_bytes;
        clamp_level(&app->feed_level);
    } else {
        app->play_level += app->pending_msg_bytes;
        clamp_level(&app->play_level);
    }
    app->pending_msg_ts = 0;
    app->pending_msg_bytes = 0;

    /* Age bump. Each classified interaction is one life experience. */
    uint32_t age = ++app->age_transactions;
    if(age == 10u || age == 50u || age == 200u || age == 1000u) {
        /* Double-length Celebrate for milestone feel. */
        set_transient(app, PetStateCelebrate, CELEBRATE_LINGER_MS * 2u);
    }
}

/* =======================================================================
 *  Persistence — /ext/apps_data/claude_buddy/state.bin
 * ======================================================================= */

static void persist_save(ClaudeBuddyApp* app) {
    Storage* storage = furi_record_open(RECORD_STORAGE);
    storage_simply_mkdir(storage, CB_STATE_DIR);

    ClaudeBuddyPersist state = {
        .magic = CB_STATE_MAGIC,
        .version = CB_STATE_VERSION,
        .play_level = app->play_level,
        .feed_level = app->feed_level,
        .age_transactions = app->age_transactions,
        .total_approvals = app->total_approvals,
        .total_denials = app->total_denials,
        .interaction_bytes = app->interaction_bytes,
        .last_saved_ms = furi_get_tick(),
    };
    memset(state.reserved, 0, sizeof(state.reserved));

    File* f = storage_file_alloc(storage);
    if(storage_file_open(f, CB_STATE_PATH, FSAM_WRITE, FSOM_CREATE_ALWAYS)) {
        storage_file_write(f, &state, sizeof(state));
        storage_file_close(f);
    }
    storage_file_free(f);
    furi_record_close(RECORD_STORAGE);

    app->last_save_ms = furi_get_tick();
}

static void persist_load(ClaudeBuddyApp* app) {
    Storage* storage = furi_record_open(RECORD_STORAGE);
    File* f = storage_file_alloc(storage);
    if(storage_file_open(f, CB_STATE_PATH, FSAM_READ, FSOM_OPEN_EXISTING)) {
        ClaudeBuddyPersist state;
        size_t n = storage_file_read(f, &state, sizeof(state));
        storage_file_close(f);
        if(n == sizeof(state) && state.magic == CB_STATE_MAGIC &&
           state.version == CB_STATE_VERSION) {
            app->play_level = state.play_level;
            app->feed_level = state.feed_level;
            app->age_transactions = state.age_transactions;
            app->total_approvals = state.total_approvals;
            app->total_denials = state.total_denials;
            app->interaction_bytes = state.interaction_bytes;
        }
        /* else: stale magic/version → keep zeros (fresh pet). */
    }
    storage_file_free(f);
    furi_record_close(RECORD_STORAGE);
}

/* Called when an unrecognized msg arrives. First resolves any prior
 * pending entry that's older than CLASSIFY_WINDOW_MS — otherwise we'd
 * lose classification of that earlier entry. Then stamps the new one. */
static void gotchi_record_msg_change(ClaudeBuddyApp* app, uint32_t bytes) {
    uint32_t now = furi_get_tick();
    if(app->pending_msg_ts && now - app->pending_msg_ts > CLASSIFY_WINDOW_MS) {
        gotchi_classify_pending(app);
    } else if(app->pending_msg_ts) {
        /* New input overrides old within window — treat the old one
         * as "ambiguous" and classify based on tokens so far. */
        gotchi_classify_pending(app);
    }
    app->pending_msg_ts = now;
    app->pending_msg_bytes = bytes;
    app->pending_start_tokens = app->hb_tokens;
}

/* Periodic tick — expires pending past window, runs decay, tracks
 * lonely/starving sustain timers. Call under app->mtx. */
static void gotchi_tick(ClaudeBuddyApp* app) {
    uint32_t now = furi_get_tick();

    /* Expire pending beyond the window. */
    if(app->pending_msg_ts && now - app->pending_msg_ts > CLASSIFY_WINDOW_MS) {
        gotchi_classify_pending(app);
    }

    /* Decay once per minute. */
    if(!app->last_decay_ms) {
        app->last_decay_ms = now;
    } else if(now - app->last_decay_ms >= DECAY_TICK_MS) {
        app->play_level = (app->play_level > PLAY_DECAY_PER_MIN) ?
                              app->play_level - PLAY_DECAY_PER_MIN : 0;
        app->feed_level = (app->feed_level > FEED_DECAY_PER_MIN) ?
                              app->feed_level - FEED_DECAY_PER_MIN : 0;
        app->last_decay_ms = now;
    }

    /* Sustain timers. */
    bool low_low = app->play_level < PLAY_LOW && app->feed_level < FEED_LOW;
    if(low_low) {
        if(!app->lonely_since_ms) app->lonely_since_ms = now;
    } else {
        app->lonely_since_ms = 0;
    }

    if(app->feed_level == 0) {
        if(!app->starving_since_ms) app->starving_since_ms = now;
    } else {
        app->starving_since_ms = 0;
    }

    /* Autosave — every 5 min while running. Storage I/O is synchronous
     * from this timer-service task context; for 60 bytes it's fast
     * enough not to cause visible hitches. */
    if(!app->last_save_ms || now - app->last_save_ms >= AUTOSAVE_INTERVAL_MS) {
        persist_save(app);
    }
}

/* Stage-keyed dispatch table: [evo stage][pet state] → Icon*. Loaded
 * in ensure_anim when the derived (stage, state) pair changes. */
#define ICONS_FOR_STAGE(stage) { \
    [PetStateSleep]        = &A_mascot_##stage##_sleep_64x64, \
    [PetStateIdle]         = &A_mascot_##stage##_idle_64x64, \
    [PetStateBusy]         = &A_mascot_##stage##_busy_64x64, \
    [PetStateOverloaded]   = &A_mascot_##stage##_overloaded_64x64, \
    [PetStateAttention]    = &A_mascot_##stage##_attention_64x64, \
    [PetStateHeart]        = &A_mascot_##stage##_heart_64x64, \
    [PetStateCelebrate]    = &A_mascot_##stage##_celebrate_64x64, \
    [PetStateReconnecting] = &A_mascot_##stage##_reconnecting_64x64, \
    [PetStateHappy]        = &A_mascot_##stage##_happy_64x64, \
    [PetStateGrumpy]       = &A_mascot_##stage##_grumpy_64x64, \
    [PetStateContent]      = &A_mascot_##stage##_content_64x64, \
    [PetStateFocused]      = &A_mascot_##stage##_focused_64x64, \
    [PetStateLonely]       = &A_mascot_##stage##_lonely_64x64, \
    [PetStateStarving]     = &A_mascot_##stage##_starving_64x64, \
}

static const Icon* const mascot_icons[EvoCount][PetStateCount] = {
    [EvoEgg]   = ICONS_FOR_STAGE(egg),
    [EvoChild] = ICONS_FOR_STAGE(child),
    [EvoTeen]  = ICONS_FOR_STAGE(teen),
    [EvoAdult] = ICONS_FOR_STAGE(adult),
    [EvoElder] = ICONS_FOR_STAGE(elder),
};
#undef ICONS_FOR_STAGE

static PetEvoStage evo_stage_from_age(uint32_t age) {
    if(age >= 1000u) return EvoElder;
    if(age >= 200u) return EvoAdult;
    if(age >= 50u) return EvoTeen;
    if(age >= 10u) return EvoChild;
    return EvoEgg;
}

static const Icon* anim_icon_for_state(PetState s, PetEvoStage e) {
    if((unsigned)s >= PetStateCount || (unsigned)e >= EvoCount) {
        return &A_mascot_child_idle_64x64;
    }
    const Icon* i = mascot_icons[e][s];
    return i ? i : &A_mascot_child_idle_64x64;
}

/* IconAnimation's internal timer fires this callback on each frame
 * advance. We tell the GUI to redraw, which pulls the new frame via
 * canvas_draw_icon_animation in the draw callback. Runs on the Timer
 * Service task — view_port_update is thread-safe. */
static void anim_update_cb(IconAnimation* instance, void* ctx) {
    UNUSED(instance);
    ClaudeBuddyApp* app = ctx;
    view_port_update(app->view_port);
}

/* Swap to the animation for the given (state, stage) pair if it's
 * not already active. Must be called with app->mtx held. Swaps fire
 * when either axis changes — pet state OR life stage transition. */
static void ensure_anim(ClaudeBuddyApp* app, PetState s) {
    PetEvoStage stage = evo_stage_from_age(app->age_transactions);
    if(app->current_anim && app->anim_state == s && app->anim_stage == stage) return;
    if(app->current_anim) {
        icon_animation_stop(app->current_anim);
        icon_animation_free(app->current_anim);
    }
    app->current_anim = icon_animation_alloc(anim_icon_for_state(s, stage));
    icon_animation_set_update_callback(app->current_anim, anim_update_cb, app);
    icon_animation_start(app->current_anim);
    app->anim_state = s;
    app->anim_stage = stage;
}

/* ============================================================
 *  Heartbeat ingest
 * ============================================================ */

static void handle_rx_line(ClaudeBuddyApp* app, const char* line, size_t line_len) {
    jsmn_parser parser;
    jsmntok_t tokens[MAX_TOKENS];
    jsmn_init(&parser);
    int n = jsmn_parse(&parser, line, line_len, tokens, MAX_TOKENS);
    if(n < 1 || tokens[0].type != JSMN_OBJECT) return;

    furi_mutex_acquire(app->mtx, FuriWaitForever);

    int v;
    if((v = json_find_key(line, tokens, n, "total")) >= 0)
        app->hb_total = json_tok_int(line, &tokens[v]);
    if((v = json_find_key(line, tokens, n, "running")) >= 0)
        app->hb_running = json_tok_int(line, &tokens[v]);
    if((v = json_find_key(line, tokens, n, "waiting")) >= 0)
        app->hb_waiting = json_tok_int(line, &tokens[v]);
    if((v = json_find_key(line, tokens, n, "msg")) >= 0) {
        char prev_msg[sizeof(app->hb_msg)];
        strlcpy(prev_msg, app->hb_msg, sizeof(prev_msg));
        json_tok_strcpy(line, &tokens[v], app->hb_msg, sizeof(app->hb_msg));

        /* Classify the new msg. Unmatched patterns are treated as
         * Claudegotchi substrate: stamp activity, accrue
         * interaction_bytes, and open a pending classification window
         * for the play/feed split. Only count on actual change to
         * avoid double-counting when the desktop re-sends the same
         * msg on its 10s keepalive. */
        if(app->hb_msg[0] && strcmp(prev_msg, app->hb_msg) != 0) {
            ClaudeBuddyMsgSummary probe;
            summarize_msg(app->hb_msg, &probe);
            if(probe.label[0] == '\0') {
                uint32_t bytes = (uint32_t)strlen(app->hb_msg);
                app->last_activity_ms = furi_get_tick();
                app->interaction_bytes += bytes;
                gotchi_record_msg_change(app, bytes);
            }
        }
    }

    /* tokens milestone (celebrate). */
    if((v = json_find_key(line, tokens, n, "tokens")) >= 0) {
        int new_tokens = json_tok_int(line, &tokens[v]);
        if(!app->tokens_baseline_set && new_tokens > 0) {
            /* First sighting — snap milestone so we don't fire
             * immediately for pre-existing tokens at app start. */
            app->last_celebrated_tokens =
                (new_tokens / TOKENS_MILESTONE) * TOKENS_MILESTONE;
            app->tokens_baseline_set = true;
        } else if(
            app->tokens_baseline_set &&
            new_tokens >= app->last_celebrated_tokens + (int)TOKENS_MILESTONE) {
            set_transient(app, PetStateCelebrate, CELEBRATE_LINGER_MS);
            app->last_celebrated_tokens =
                (new_tokens / TOKENS_MILESTONE) * TOKENS_MILESTONE;
        }
        app->hb_tokens = new_tokens;
    }

    ClaudeBuddyMode prev_mode = app->mode;
    int p_idx = json_find_key(line, tokens, n, "prompt");
    if(p_idx >= 0 && tokens[p_idx].type == JSMN_OBJECT) {
        if((v = json_find_key(line, tokens, n, "id")) >= 0)
            json_tok_strcpy(line, &tokens[v], app->prompt_id, sizeof(app->prompt_id));
        if((v = json_find_key(line, tokens, n, "tool")) >= 0)
            json_tok_strcpy(line, &tokens[v], app->prompt_tool, sizeof(app->prompt_tool));
        if((v = json_find_key(line, tokens, n, "hint")) >= 0)
            json_tok_strcpy(line, &tokens[v], app->prompt_hint, sizeof(app->prompt_hint));
        app->mode = ClaudeBuddyModePrompt;
    } else {
        /* Desktop cleared the prompt — drop the modal. */
        app->mode = ClaudeBuddyModeNormal;
    }
    bool entering_prompt = (prev_mode != ClaudeBuddyModePrompt) &&
                           (app->mode == ClaudeBuddyModePrompt);
    if(entering_prompt) {
        /* Stamp the time so the input handler can detect fast approval. */
        app->prompt_shown_at_ms = furi_get_tick();
    }

    ensure_anim(app, pet_state_derive(app));

    furi_mutex_release(app->mtx);

    /* On the Normal → Prompt edge: buzz to grab attention, AND kick the
     * display backlight back on if it's gone to sleep — otherwise the
     * user might miss the modal entirely if they walked away. Don't
     * re-fire on subsequent heartbeats while already in the modal. */
    if(entering_prompt && app->notifications) {
        notification_message(app->notifications, &sequence_single_vibro);
        notification_message(app->notifications, &sequence_display_backlight_on);
    }

    view_port_update(app->view_port);
}

/* ============================================================
 *  RX drain thread
 * ============================================================ */

static int32_t claude_buddy_rx_thread(void* ctx) {
    ClaudeBuddyApp* app = ctx;
    uint8_t chunk[64];
    while(app->running) {
        size_t n =
            furi_stream_buffer_receive(app->rx_stream, chunk, sizeof(chunk), 250);
        for(size_t i = 0; i < n; i++) {
            if(app->line_len < LINE_BUF_SIZE - 1) {
                app->line_buf[app->line_len++] = chunk[i];
            } else {
                /* Over-long line — reset and drop until the next newline. */
                app->line_len = 0;
            }
            if(chunk[i] == '\n') {
                handle_rx_line(app, (const char*)app->line_buf, app->line_len);
                app->line_len = 0;
            }
        }
    }
    return 0;
}

/* ============================================================
 *  Drawing
 * ============================================================ */

static void claude_buddy_draw(Canvas* canvas, void* ctx) {
    ClaudeBuddyApp* app = ctx;

    /* Hold the mutex for the whole draw. We need current_anim to stay
     * valid while canvas_draw_icon_animation reads its frame data.
     * Swap-anim sites also hold the mutex, so they can't free
     * current_anim under us here. */
    furi_mutex_acquire(app->mtx, FuriWaitForever);

    /* Re-derive state every draw — picks up transient expiry
     * (heart/celebrate/reconnecting fading back) without needing the
     * swap sites to know about the timeout. ensure_anim is a no-op if
     * state didn't change, so cost is just the derive + a comparison. */
    ensure_anim(app, pet_state_derive(app));

    ClaudeBuddyMode mode = app->mode;
    BtStatus bt_status = app->bt_status;
    bool cccd = app->cccd_enabled;
    int t = app->hb_total, r = app->hb_running, w = app->hb_waiting;

    canvas_clear(canvas);

    if(mode == ClaudeBuddyModePrompt) {
        /* Prompt modal: attention mascot on the left, stripped-down
         * decision surface on the right.
         *   - "Allow?" (PRIMARY, grabby header)
         *   - Tool name in FontSecondary below (just context)
         *   - OK/Left keybindings at the bottom */
        if(app->current_anim) {
            canvas_draw_icon_animation(canvas, 0, 0, app->current_anim);
        }

        canvas_set_font(canvas, FontPrimary);
        canvas_draw_str(canvas, 66, 14, "Allow?");

        canvas_set_font(canvas, FontSecondary);
        canvas_draw_str(canvas, 66, 28, app->prompt_tool);

        canvas_draw_str(canvas, 66, 52, "OK:yes");
        canvas_draw_str(canvas, 66, 62, "L:deny");

        furi_mutex_release(app->mtx);
        return;
    }

    /* Normal mode: mascot carries the state signal (state-driven frames
     * cover sleep/idle/busy/attention, plus blue LED for connected).
     * Right column is deliberately minimal: just a title block and the
     * current msg. Removed BT status line + T/R/W counters — they
     * duplicated info the mascot already conveys, and the msg has
     * more room to breathe now. */
    (void)bt_status;
    (void)cccd;
    (void)t;
    (void)r;
    (void)w;

    if(app->current_anim) {
        canvas_draw_icon_animation(canvas, 0, 0, app->current_anim);
    }

    /* Title "Claude" in FontPrimary — the brand mark at the biggest
     * readable size that fits. "ClaudeBuddy" and "Claudebuddy" both
     * clipped the final letter at 62 px of column width; 6 chars
     * leaves slack. The mascot itself provides the "Buddy" signal. */
    canvas_set_font(canvas, FontPrimary);
    canvas_draw_str(canvas, 66, 12, "Claude");

    /* Summarized msg: only recognized status patterns render. Free-form
     * text (including what the user is typing into Claude Code) is
     * deliberately NOT shown — bare user input on a pocket-sized screen
     * is a privacy leak. When an unrecognized msg recently arrived,
     * show a pulsing "…" instead to acknowledge "something's happening"
     * without surfacing the content. */
    ClaudeBuddyMsgSummary sum;
    summarize_msg(app->hb_msg, &sum);
    if(sum.label[0]) {
        canvas_set_font(canvas, FontPrimary);
        canvas_draw_str(canvas, 66, 36, sum.label);
        if(sum.detail[0]) {
            canvas_set_font(canvas, FontSecondary);
            canvas_draw_str(canvas, 66, 50, sum.detail);
        }
    } else {
        /* No known label → Claudegotchi panel:
         *   H (Happy): play_level / LEVEL_MAX
         *   F (Food):  feed_level / LEVEL_MAX
         *   T: age (transactions) — raw number
         *   "typing" flash when a recent unrecognized msg arrived
         * Bars fill positively (high = good, not the classic Tamagotchi
         * inverse-need convention). */
        canvas_set_font(canvas, FontSecondary);

        const int bx = 74, bw = 52, bh = 5;
        canvas_draw_str(canvas, 66, 30, "H");
        canvas_draw_frame(canvas, bx, 25, bw, bh);
        uint32_t pfill = (app->play_level * (bw - 2)) / LEVEL_MAX;
        if(pfill > 0) canvas_draw_box(canvas, bx + 1, 26, (int)pfill, bh - 2);

        canvas_draw_str(canvas, 66, 42, "F");
        canvas_draw_frame(canvas, bx, 37, bw, bh);
        uint32_t ffill = (app->feed_level * (bw - 2)) / LEVEL_MAX;
        if(ffill > 0) canvas_draw_box(canvas, bx + 1, 38, (int)ffill, bh - 2);

        /* Age readout. Combines with "..." typing indicator on the same
         * line so they don't collide in the 62-px column. */
        uint32_t now = furi_get_tick();
        bool typing = app->last_activity_ms && now - app->last_activity_ms < 2000u;
        char age_line[20];
        snprintf(
            age_line,
            sizeof(age_line),
            typing ? "Age:%lu ..." : "Age:%lu",
            (unsigned long)app->age_transactions);
        canvas_draw_str(canvas, 66, 52, age_line);
    }

    /* Power overlays: upper-right 8x8 corner.
     *   - Charging (USB plugged in): lightning bolt
     *   - Low battery (<20%): battery warning icon
     * Charging takes priority over low — if both (e.g. starting to
     * charge at 10%), user sees the "it's being fed" glyph first. */
    if(furi_hal_power_is_charging()) {
        canvas_draw_icon(canvas, 120, 0, &I_overlay_charging_8x8);
    } else if(furi_hal_power_get_pct() < LOW_BATTERY_PCT) {
        canvas_draw_icon(canvas, 120, 0, &I_overlay_hungry_8x8);
    }

    furi_mutex_release(app->mtx);
}

/* ============================================================
 *  Input + BT callbacks
 * ============================================================ */

static void claude_buddy_input(InputEvent* event, void* ctx) {
    ClaudeBuddyApp* app = ctx;
    furi_message_queue_put(app->input_queue, event, FuriWaitForever);
}

static void claude_buddy_redraw_tick(void* ctx) {
    ClaudeBuddyApp* app = ctx;
    /* Tamagotchi tick: decay, expire pending classifications, track
     * lonely/starving sustain timers. Runs at 4 Hz (REDRAW_PERIOD_MS)
     * so lonely/starving transitions are picked up within ~250ms. */
    furi_mutex_acquire(app->mtx, FuriWaitForever);
    gotchi_tick(app);
    furi_mutex_release(app->mtx);
    view_port_update(app->view_port);
}

static void claude_buddy_on_bt_status(BtStatus status, void* ctx) {
    ClaudeBuddyApp* app = ctx;
    furi_mutex_acquire(app->mtx, FuriWaitForever);
    BtStatus prev = app->bt_status;
    app->bt_status = status;

    /* Reconnecting transient: was Connected, now Advertising. */
    if(prev == BtStatusConnected && status == BtStatusAdvertising) {
        set_transient(app, PetStateReconnecting, RECONNECTING_LINGER_MS);
    }
    if(status == BtStatusConnected) {
        app->was_connected = true;
    }

    ensure_anim(app, pet_state_derive(app));
    furi_mutex_release(app->mtx);

    /* Blue LED while a central is connected, off otherwise — mirrors
     * hid_app/hid.c:100. Small quality-of-life indicator that matches
     * stock Flipper UX conventions for BLE apps. */
    if(app->notifications) {
        notification_message(
            app->notifications,
            status == BtStatusConnected ? &sequence_set_blue_255 : &sequence_reset_blue);
    }
}

static void claude_buddy_on_rx(const uint8_t* data, uint16_t len, void* ctx) {
    ClaudeBuddyApp* app = ctx;
    /* BLE thread context — push bytes and return fast. */
    furi_stream_buffer_send(app->rx_stream, data, len, 0);
}

static void claude_buddy_on_conn(bool connected, void* ctx) {
    ClaudeBuddyApp* app = ctx;
    furi_mutex_acquire(app->mtx, FuriWaitForever);
    app->cccd_enabled = connected;
    furi_mutex_release(app->mtx);
}

/* ============================================================
 *  Entry point
 * ============================================================ */

int32_t claude_buddy_app(void* p) {
    UNUSED(p);
    ClaudeBuddyApp* app = malloc(sizeof(ClaudeBuddyApp));
    memset(app, 0, sizeof(*app));

    app->mtx = furi_mutex_alloc(FuriMutexTypeNormal);
    app->input_queue = furi_message_queue_alloc(8, sizeof(InputEvent));
    app->rx_stream = furi_stream_buffer_alloc(RX_STREAM_SIZE, RX_STREAM_TRIGGER);
    app->running = true;
    app->notifications = furi_record_open(RECORD_NOTIFICATION);

    /* Restore persisted Tamagotchi stats before doing anything else —
     * the pet remembers across reboots. */
    persist_load(app);

    /* Start with the sleep animation — we haven't connected to anyone
     * yet and heartbeat hasn't been parsed. Will swap as state evolves. */
    furi_mutex_acquire(app->mtx, FuriWaitForever);
    ensure_anim(app, PetStateSleep);
    furi_mutex_release(app->mtx);

    app->view_port = view_port_alloc();
    view_port_draw_callback_set(app->view_port, claude_buddy_draw, app);
    view_port_input_callback_set(app->view_port, claude_buddy_input, app);
    app->gui = furi_record_open(RECORD_GUI);
    gui_add_view_port(app->gui, app->view_port, GuiLayerFullscreen);
    app->redraw_timer = furi_timer_alloc(claude_buddy_redraw_tick, FuriTimerTypePeriodic, app);
    furi_timer_start(app->redraw_timer, REDRAW_PERIOD_MS);

    /* RX drain thread */
    app->rx_thread = furi_thread_alloc_ex("ClaudeBuddyRx", RX_THREAD_STACK, claude_buddy_rx_thread, app);
    furi_thread_start(app->rx_thread);

    /* Bring up BLE */
    app->bt = furi_record_open(RECORD_BT);
    bt_set_status_changed_callback(app->bt, claude_buddy_on_bt_status, app);
    app->profile = bt_profile_start(app->bt, ble_profile_claude_buddy, NULL);
    if(!app->profile) {
        FURI_LOG_E(TAG, "bt_profile_start failed");
    } else {
        claude_buddy_profile_set_rx_callback(app->profile, claude_buddy_on_rx, app);
        claude_buddy_profile_set_conn_callback(app->profile, claude_buddy_on_conn, app);
    }

    /* Main input loop */
    InputEvent event;
    while(furi_message_queue_get(app->input_queue, &event, FuriWaitForever) == FuriStatusOk) {
        if(event.type != InputTypeShort) continue;

        /* Back always exits, regardless of mode. */
        if(event.key == InputKeyBack) break;

        /* Snapshot mode + prompt id for the handler below. */
        furi_mutex_acquire(app->mtx, FuriWaitForever);
        ClaudeBuddyMode mode = app->mode;
        char id[48];
        strlcpy(id, app->prompt_id, sizeof(id));
        furi_mutex_release(app->mtx);

        if(mode != ClaudeBuddyModePrompt) continue;
        if(id[0] == '\0') continue;

        const char* decision = NULL;
        if(event.key == InputKeyOk) decision = "once";
        else if(event.key == InputKeyLeft) decision = "deny";
        if(!decision) continue;

        bool tx_ok = false;
        if(app->profile) {
            char json[160];
            int n = snprintf(
                json,
                sizeof(json),
                "{\"cmd\":\"permission\",\"id\":\"%s\",\"decision\":\"%s\"}\n",
                id,
                decision);
            if(n > 0 && (size_t)n < sizeof(json)) {
                tx_ok = claude_buddy_profile_tx(
                    app->profile, (const uint8_t*)json, (uint16_t)n);
            }
        }

        /* Dismiss modal locally regardless of TX result — immediate
         * visual ack. Note the result on the status line so the user
         * can distinguish "sent" from "tried but BLE refused". Also
         * update streak counters + heart-transient here so the pet's
         * mood reflects the decision immediately. */
        furi_mutex_acquire(app->mtx, FuriWaitForever);
        app->mode = ClaudeBuddyModeNormal;
        app->prompt_id[0] = '\0';
        snprintf(
            app->hb_msg,
            sizeof(app->hb_msg),
            "sent: %s (%s)",
            decision,
            tx_ok ? "ok" : "fail");

        uint32_t now = furi_get_tick();
        bool approved = (event.key == InputKeyOk);
        if(approved) {
            app->approval_streak++;
            app->denial_streak = 0;
            app->total_approvals++;
            /* Heart if approval happened within 5s of the prompt arriving. */
            if(app->prompt_shown_at_ms &&
               now - app->prompt_shown_at_ms < HEART_TRIGGER_MS) {
                set_transient(app, PetStateHeart, HEART_LINGER_MS);
            }
        } else {
            app->denial_streak++;
            app->approval_streak = 0;
            app->total_denials++;
        }

        ensure_anim(app, pet_state_derive(app));
        furi_mutex_release(app->mtx);
        view_port_update(app->view_port);
    }

    /* Teardown: stop drain thread, then tear down BLE, then GUI. */
    app->running = false;
    furi_thread_join(app->rx_thread);
    furi_thread_free(app->rx_thread);

    /* Flush Tamagotchi stats to SD before losing anything else. */
    persist_save(app);

    if(app->profile) {
        bt_profile_restore_default(app->bt);
    }
    bt_set_status_changed_callback(app->bt, NULL, NULL);
    furi_record_close(RECORD_BT);

    /* Make sure the LED is off when we leave. */
    notification_message(app->notifications, &sequence_reset_blue);
    furi_record_close(RECORD_NOTIFICATION);

    furi_timer_stop(app->redraw_timer);
    furi_timer_free(app->redraw_timer);
    gui_remove_view_port(app->gui, app->view_port);
    view_port_free(app->view_port);
    furi_record_close(RECORD_GUI);

    /* Animation after view_port — the icon-animation timer could have
     * fired a view_port_update between our gui_remove_view_port and
     * view_port_free. Stopping the animation first avoids that race. */
    if(app->current_anim) {
        icon_animation_stop(app->current_anim);
        icon_animation_free(app->current_anim);
    }

    furi_stream_buffer_free(app->rx_stream);
    furi_message_queue_free(app->input_queue);
    furi_mutex_free(app->mtx);
    free(app);
    return 0;
}
