/* Phase 3: heartbeat JSON rendering + permission-prompt modal.
 *
 * Architecture:
 *   - BLE RX callback (BLE thread) pushes raw bytes into a FuriStreamBuffer.
 *   - A dedicated drain thread accumulates bytes into a line buffer, parses
 *     one JSON object per '\n' with jsmn, and updates shared app state
 *     under a mutex.
 *   - The main thread drives the GUI: a redraw timer at 4 Hz polls state
 *     and repaints, and an input queue handles button events.
 *   - When the parsed heartbeat contains a `prompt` object, the app enters
 *     ModePrompt and renders a modal with tool/hint + keybindings. OK and
 *     Left send the permission response back via TX; the desktop clears
 *     the prompt from subsequent heartbeats, which drops us back to
 *     ModeNormal.
 */

#include "claude_buddy_profile.h"

#include <furi.h>
#include <furi_hal_version.h>
#include <bt/bt_service/bt.h>
#include <gui/gui.h>
#include <gui/view_port.h>
#include <input/input.h>
#include <notification/notification_messages.h>
#include <gui/icon_animation.h>

/* Generated by the build from PNGs under claude_buddy/assets/ — exposes
 * the compiled Icon symbols. Animated subdirs (with a frame_rate file)
 * produce A_* Icons; each is wrapped in an IconAnimation at runtime. */
#include "claude_buddy_icons.h"

#define JSMN_STATIC
#include "jsmn.h"

#include <stdlib.h>
#include <string.h>

#define TAG "ClaudeBuddyApp"

#define REDRAW_PERIOD_MS    250
#define LINE_BUF_SIZE       1024
#define RX_STREAM_SIZE      2048
#define RX_STREAM_TRIGGER   1
#define RX_THREAD_STACK     2048
#define MAX_TOKENS          64

typedef enum {
    ClaudeBuddyModeNormal,
    ClaudeBuddyModePrompt,
} ClaudeBuddyMode;

/* Visible pet state, derived from BT connection + heartbeat counts. */
typedef enum {
    PetStateSleep,      /* disconnected, or nothing open on the desktop */
    PetStateIdle,       /* connected + sessions open but not generating */
    PetStateBusy,       /* running > 0 */
    PetStateAttention,  /* waiting > 0 or modal open — decision needed */
} PetState;

typedef struct {
    FuriMutex* mtx;

    /* BT status */
    BtStatus bt_status;
    bool cccd_enabled;

    /* Parsed heartbeat fields */
    int hb_total;
    int hb_running;
    int hb_waiting;
    char hb_msg[64];

    /* Prompt state (valid when mode == Prompt) */
    ClaudeBuddyMode mode;
    char prompt_id[48];
    char prompt_tool[32];
    char prompt_hint[96];

    /* GUI */
    FuriMessageQueue* input_queue;
    ViewPort* view_port;
    Gui* gui;
    FuriTimer* redraw_timer;

    /* RX pipeline */
    FuriStreamBuffer* rx_stream;
    FuriThread* rx_thread;
    volatile bool running;
    uint8_t line_buf[LINE_BUF_SIZE];
    size_t line_len;

    /* BT service + active profile */
    Bt* bt;
    FuriHalBleProfileBase* profile;

    /* LED / haptic */
    NotificationApp* notifications;

    /* Currently-playing mascot animation. Swapped by ensure_anim()
     * when the derived pet state changes. Guarded by app->mtx. */
    IconAnimation* current_anim;
    PetState anim_state;
} ClaudeBuddyApp;

/* Forward so callbacks can reference the struct. */
static void ensure_anim(ClaudeBuddyApp* app, PetState s);

/* ============================================================
 *  JSON helpers — small wrappers on jsmn
 * ============================================================ */

static bool tok_streq(const char* json, const jsmntok_t* t, const char* s) {
    int len = t->end - t->start;
    return (int)strlen(s) == len && strncmp(json + t->start, s, len) == 0;
}

/* Linear key search: find the first STRING token matching `key` and
 * return the index of the immediately following (value) token. Good
 * enough for the Hardware Buddy heartbeat since all keys we care about
 * are globally unique across the object (total/running/waiting/msg at
 * top level; id/tool/hint only under `prompt`). Returns -1 if not
 * found. */
static int json_find_key(const char* json, const jsmntok_t* tokens, int n, const char* key) {
    for(int i = 0; i < n - 1; i++) {
        if(tokens[i].type == JSMN_STRING && tok_streq(json, &tokens[i], key)) {
            return i + 1;
        }
    }
    return -1;
}

static int json_tok_int(const char* json, const jsmntok_t* t) {
    char buf[16] = {0};
    int len = t->end - t->start;
    if(len < 0 || len >= (int)sizeof(buf)) return 0;
    memcpy(buf, json + t->start, len);
    return atoi(buf);
}

static void
    json_tok_strcpy(const char* json, const jsmntok_t* t, char* dst, size_t dst_size) {
    int len = t->end - t->start;
    if(len < 0) len = 0;
    if(len >= (int)dst_size) len = dst_size - 1;
    memcpy(dst, json + t->start, len);
    dst[len] = '\0';
}

/* Summarize a free-form heartbeat `msg` string into a short label
 * (≤ 5 chars) plus an optional detail word. The desktop's msg field is
 * "one-line summary suitable for a small display" per REFERENCE.md, but
 * in practice still too long for 64 px of right-column font-secondary.
 * Common observed patterns:
 *     "running: yarn test"      → RUN / yarn
 *     "approve: Bash"           → ASK / Bash
 *     "called bash"             → RUN / bash
 *     "done(success), 1 turns"  → DONE
 *     "done(failure), …"        → FAIL
 *     "approved"                → OK
 *     <anything else>           → raw msg in detail, no label
 * Extend the ladder here as new desktop patterns surface. */
typedef struct {
    char label[8];    /* 1-5 char summary, rendered in FontPrimary */
    char detail[24];  /* optional trailing word(s), FontSecondary */
} ClaudeBuddyMsgSummary;

static void copy_first_word(const char* src, char* dst, size_t dst_size) {
    while(*src == ' ') src++;
    size_t n = 0;
    while(*src && *src != ' ' && n < dst_size - 1) {
        dst[n++] = *src++;
    }
    dst[n] = '\0';
}

static void summarize_msg(const char* raw, ClaudeBuddyMsgSummary* s) {
    s->label[0] = '\0';
    s->detail[0] = '\0';
    if(!raw || !raw[0]) return;

    /* Desktop sometimes wraps msg in parens, e.g. "(called Bash)".
     * Strip a leading "(" so pattern matching works uniformly. */
    const char* p = raw;
    if(*p == '(') p++;

    if(strncmp(p, "running:", 8) == 0) {
        strlcpy(s->label, "RUN", sizeof(s->label));
        copy_first_word(p + 8, s->detail, sizeof(s->detail));
    } else if(strncmp(p, "approve:", 8) == 0) {
        strlcpy(s->label, "ASK", sizeof(s->label));
        copy_first_word(p + 8, s->detail, sizeof(s->detail));
    } else if(strncmp(p, "called ", 7) == 0) {
        strlcpy(s->label, "RUN", sizeof(s->label));
        copy_first_word(p + 7, s->detail, sizeof(s->detail));
    } else if(strncmp(p, "done(success", 12) == 0) {
        strlcpy(s->label, "DONE", sizeof(s->label));
    } else if(
        strncmp(p, "done(failure", 12) == 0 || strncmp(p, "done(error", 10) == 0 ||
        strncmp(p, "failed", 6) == 0) {
        strlcpy(s->label, "FAIL", sizeof(s->label));
    } else if(strcmp(p, "approved") == 0) {
        strlcpy(s->label, "OK", sizeof(s->label));
    } else if(strcmp(p, "denied") == 0) {
        strlcpy(s->label, "NO", sizeof(s->label));
    } else {
        /* Unknown pattern — show the raw text truncated, no label. */
        strlcpy(s->detail, raw, sizeof(s->detail));
    }

    /* Trim a trailing ")" that the paren-wrap leaves behind in detail. */
    size_t n = strlen(s->detail);
    if(n > 0 && s->detail[n - 1] == ')') s->detail[n - 1] = '\0';
}

/* Derive pet visible state from the live fields. Call under app->mtx
 * (reads multiple fields; caller must hold the lock). */
static PetState pet_state_from_app(
    BtStatus bt,
    ClaudeBuddyMode mode,
    int running,
    int waiting,
    int total) {
    if(bt != BtStatusConnected) return PetStateSleep;
    if(mode == ClaudeBuddyModePrompt || waiting > 0) return PetStateAttention;
    if(running > 0) return PetStateBusy;
    if(total > 0) return PetStateIdle;
    return PetStateSleep;
}

/* Map a pet state to its animated icon asset. Called by ensure_anim()
 * whenever the derived state changes; not called in the draw path. */
static const Icon* anim_icon_for_state(PetState s) {
    switch(s) {
    case PetStateSleep: return &A_mascot_sleep_64x64;
    case PetStateBusy: return &A_mascot_busy_64x64;
    case PetStateAttention: return &A_mascot_attention_64x64;
    case PetStateIdle: /* fall through */
    default: return &A_mascot_idle_64x64;
    }
}

/* IconAnimation's internal timer fires this callback on each frame
 * advance. We tell the GUI to redraw, which pulls the new frame via
 * canvas_draw_icon_animation in the draw callback. Runs on the Timer
 * Service task — view_port_update is thread-safe. */
static void anim_update_cb(IconAnimation* instance, void* ctx) {
    UNUSED(instance);
    ClaudeBuddyApp* app = ctx;
    view_port_update(app->view_port);
}

/* Swap to the animation for the given state if it's not already
 * active. Must be called with app->mtx held. */
static void ensure_anim(ClaudeBuddyApp* app, PetState s) {
    if(app->current_anim && app->anim_state == s) return;
    if(app->current_anim) {
        icon_animation_stop(app->current_anim);
        icon_animation_free(app->current_anim);
    }
    app->current_anim = icon_animation_alloc(anim_icon_for_state(s));
    icon_animation_set_update_callback(app->current_anim, anim_update_cb, app);
    icon_animation_start(app->current_anim);
    app->anim_state = s;
}

/* ============================================================
 *  Heartbeat ingest
 * ============================================================ */

static void handle_rx_line(ClaudeBuddyApp* app, const char* line, size_t line_len) {
    jsmn_parser parser;
    jsmntok_t tokens[MAX_TOKENS];
    jsmn_init(&parser);
    int n = jsmn_parse(&parser, line, line_len, tokens, MAX_TOKENS);
    if(n < 1 || tokens[0].type != JSMN_OBJECT) return;

    furi_mutex_acquire(app->mtx, FuriWaitForever);

    int v;
    if((v = json_find_key(line, tokens, n, "total")) >= 0)
        app->hb_total = json_tok_int(line, &tokens[v]);
    if((v = json_find_key(line, tokens, n, "running")) >= 0)
        app->hb_running = json_tok_int(line, &tokens[v]);
    if((v = json_find_key(line, tokens, n, "waiting")) >= 0)
        app->hb_waiting = json_tok_int(line, &tokens[v]);
    if((v = json_find_key(line, tokens, n, "msg")) >= 0)
        json_tok_strcpy(line, &tokens[v], app->hb_msg, sizeof(app->hb_msg));

    ClaudeBuddyMode prev_mode = app->mode;
    int p_idx = json_find_key(line, tokens, n, "prompt");
    if(p_idx >= 0 && tokens[p_idx].type == JSMN_OBJECT) {
        if((v = json_find_key(line, tokens, n, "id")) >= 0)
            json_tok_strcpy(line, &tokens[v], app->prompt_id, sizeof(app->prompt_id));
        if((v = json_find_key(line, tokens, n, "tool")) >= 0)
            json_tok_strcpy(line, &tokens[v], app->prompt_tool, sizeof(app->prompt_tool));
        if((v = json_find_key(line, tokens, n, "hint")) >= 0)
            json_tok_strcpy(line, &tokens[v], app->prompt_hint, sizeof(app->prompt_hint));
        app->mode = ClaudeBuddyModePrompt;
    } else {
        /* Desktop cleared the prompt — drop the modal. */
        app->mode = ClaudeBuddyModeNormal;
    }
    bool entering_prompt = (prev_mode != ClaudeBuddyModePrompt) &&
                           (app->mode == ClaudeBuddyModePrompt);

    /* Re-derive pet state from the updated fields and swap the
     * animation if it changed. */
    ensure_anim(app,
                pet_state_from_app(app->bt_status, app->mode, app->hb_running,
                                    app->hb_waiting, app->hb_total));

    furi_mutex_release(app->mtx);

    /* Buzz on the Normal → Prompt edge so the user notices a decision is
     * waiting. Don't re-buzz on subsequent heartbeats while already in
     * the modal — that would vibrate every 10s until they respond. */
    if(entering_prompt && app->notifications) {
        notification_message(app->notifications, &sequence_single_vibro);
    }

    view_port_update(app->view_port);
}

/* ============================================================
 *  RX drain thread
 * ============================================================ */

static int32_t claude_buddy_rx_thread(void* ctx) {
    ClaudeBuddyApp* app = ctx;
    uint8_t chunk[64];
    while(app->running) {
        size_t n =
            furi_stream_buffer_receive(app->rx_stream, chunk, sizeof(chunk), 250);
        for(size_t i = 0; i < n; i++) {
            if(app->line_len < LINE_BUF_SIZE - 1) {
                app->line_buf[app->line_len++] = chunk[i];
            } else {
                /* Over-long line — reset and drop until the next newline. */
                app->line_len = 0;
            }
            if(chunk[i] == '\n') {
                handle_rx_line(app, (const char*)app->line_buf, app->line_len);
                app->line_len = 0;
            }
        }
    }
    return 0;
}

/* ============================================================
 *  Drawing
 * ============================================================ */

static void claude_buddy_draw(Canvas* canvas, void* ctx) {
    ClaudeBuddyApp* app = ctx;

    /* Hold the mutex for the whole draw. We need current_anim to stay
     * valid while canvas_draw_icon_animation reads its frame data.
     * Swap-anim sites (handle_rx_line, on_bt_status) also hold the
     * mutex, so they can't free current_anim under us here. */
    furi_mutex_acquire(app->mtx, FuriWaitForever);
    ClaudeBuddyMode mode = app->mode;
    BtStatus bt_status = app->bt_status;
    bool cccd = app->cccd_enabled;
    int t = app->hb_total, r = app->hb_running, w = app->hb_waiting;

    canvas_clear(canvas);

    if(mode == ClaudeBuddyModePrompt) {
        /* Prompt modal: attention mascot (animated) on the left, tool /
         * hint / keybindings stacked in the right 64 px. */
        if(app->current_anim) {
            canvas_draw_icon_animation(canvas, 0, 0, app->current_anim);
        }

        canvas_set_font(canvas, FontPrimary);
        canvas_draw_str(canvas, 66, 10, "Allow?");

        canvas_set_font(canvas, FontSecondary);
        char line[32];
        snprintf(line, sizeof(line), "%s", app->prompt_tool);
        canvas_draw_str(canvas, 66, 22, line);
        strlcpy(line, app->prompt_hint, sizeof(line));
        canvas_draw_str(canvas, 66, 34, line);
        canvas_draw_str(canvas, 66, 52, "OK:yes");
        canvas_draw_str(canvas, 66, 62, "L:deny");

        furi_mutex_release(app->mtx);
        return;
    }

    /* Normal mode: mascot carries the state signal (state-driven frames
     * cover sleep/idle/busy/attention, plus blue LED for connected).
     * Right column is deliberately minimal: just a title block and the
     * current msg. Removed BT status line + T/R/W counters — they
     * duplicated info the mascot already conveys, and the msg has
     * more room to breathe now. */
    (void)bt_status;
    (void)cccd;
    (void)t;
    (void)r;
    (void)w;

    if(app->current_anim) {
        canvas_draw_icon_animation(canvas, 0, 0, app->current_anim);
    }

    /* Title: "Claudebuddy" in FontPrimary. Lowercase 'b' is narrower
     * than capital 'B' in the haxrcorp proportional font, buying us
     * ~1 px vs "ClaudeBuddy" which previously clipped the final 'y'. */
    canvas_set_font(canvas, FontPrimary);
    canvas_draw_str(canvas, 66, 12, "Claudebuddy");

    /* Summarized msg centered in the freed vertical space:
     *   label in FontPrimary for punch (RUN/ASK/DONE/FAIL/OK/NO)
     *   detail word in FontSecondary underneath
     * Unknown/free-form falls back to raw msg in FontSecondary, no label. */
    ClaudeBuddyMsgSummary sum;
    summarize_msg(app->hb_msg, &sum);
    if(sum.label[0]) {
        canvas_set_font(canvas, FontPrimary);
        canvas_draw_str(canvas, 66, 36, sum.label);
        if(sum.detail[0]) {
            canvas_set_font(canvas, FontSecondary);
            canvas_draw_str(canvas, 66, 50, sum.detail);
        }
    } else {
        canvas_set_font(canvas, FontSecondary);
        canvas_draw_str(canvas, 66, 42, sum.detail[0] ? sum.detail : "(waiting)");
    }

    furi_mutex_release(app->mtx);
}

/* ============================================================
 *  Input + BT callbacks
 * ============================================================ */

static void claude_buddy_input(InputEvent* event, void* ctx) {
    ClaudeBuddyApp* app = ctx;
    furi_message_queue_put(app->input_queue, event, FuriWaitForever);
}

static void claude_buddy_redraw_tick(void* ctx) {
    ClaudeBuddyApp* app = ctx;
    view_port_update(app->view_port);
}

static void claude_buddy_on_bt_status(BtStatus status, void* ctx) {
    ClaudeBuddyApp* app = ctx;
    furi_mutex_acquire(app->mtx, FuriWaitForever);
    app->bt_status = status;
    ensure_anim(app,
                pet_state_from_app(app->bt_status, app->mode, app->hb_running,
                                    app->hb_waiting, app->hb_total));
    furi_mutex_release(app->mtx);

    /* Blue LED while a central is connected, off otherwise — mirrors
     * hid_app/hid.c:100. Small quality-of-life indicator that matches
     * stock Flipper UX conventions for BLE apps. */
    if(app->notifications) {
        notification_message(
            app->notifications,
            status == BtStatusConnected ? &sequence_set_blue_255 : &sequence_reset_blue);
    }
}

static void claude_buddy_on_rx(const uint8_t* data, uint16_t len, void* ctx) {
    ClaudeBuddyApp* app = ctx;
    /* BLE thread context — push bytes and return fast. */
    furi_stream_buffer_send(app->rx_stream, data, len, 0);
}

static void claude_buddy_on_conn(bool connected, void* ctx) {
    ClaudeBuddyApp* app = ctx;
    furi_mutex_acquire(app->mtx, FuriWaitForever);
    app->cccd_enabled = connected;
    furi_mutex_release(app->mtx);
}

/* ============================================================
 *  Entry point
 * ============================================================ */

int32_t claude_buddy_app(void* p) {
    UNUSED(p);
    ClaudeBuddyApp* app = malloc(sizeof(ClaudeBuddyApp));
    memset(app, 0, sizeof(*app));

    app->mtx = furi_mutex_alloc(FuriMutexTypeNormal);
    app->input_queue = furi_message_queue_alloc(8, sizeof(InputEvent));
    app->rx_stream = furi_stream_buffer_alloc(RX_STREAM_SIZE, RX_STREAM_TRIGGER);
    app->running = true;
    app->notifications = furi_record_open(RECORD_NOTIFICATION);

    /* Start with the sleep animation — we haven't connected to anyone
     * yet and heartbeat hasn't been parsed. Will swap as state evolves. */
    furi_mutex_acquire(app->mtx, FuriWaitForever);
    ensure_anim(app, PetStateSleep);
    furi_mutex_release(app->mtx);

    app->view_port = view_port_alloc();
    view_port_draw_callback_set(app->view_port, claude_buddy_draw, app);
    view_port_input_callback_set(app->view_port, claude_buddy_input, app);
    app->gui = furi_record_open(RECORD_GUI);
    gui_add_view_port(app->gui, app->view_port, GuiLayerFullscreen);
    app->redraw_timer = furi_timer_alloc(claude_buddy_redraw_tick, FuriTimerTypePeriodic, app);
    furi_timer_start(app->redraw_timer, REDRAW_PERIOD_MS);

    /* RX drain thread */
    app->rx_thread = furi_thread_alloc_ex("ClaudeBuddyRx", RX_THREAD_STACK, claude_buddy_rx_thread, app);
    furi_thread_start(app->rx_thread);

    /* Bring up BLE */
    app->bt = furi_record_open(RECORD_BT);
    bt_set_status_changed_callback(app->bt, claude_buddy_on_bt_status, app);
    app->profile = bt_profile_start(app->bt, ble_profile_claude_buddy, NULL);
    if(!app->profile) {
        FURI_LOG_E(TAG, "bt_profile_start failed");
    } else {
        claude_buddy_profile_set_rx_callback(app->profile, claude_buddy_on_rx, app);
        claude_buddy_profile_set_conn_callback(app->profile, claude_buddy_on_conn, app);
    }

    /* Main input loop */
    InputEvent event;
    while(furi_message_queue_get(app->input_queue, &event, FuriWaitForever) == FuriStatusOk) {
        if(event.type != InputTypeShort) continue;

        /* Back always exits, regardless of mode. */
        if(event.key == InputKeyBack) break;

        /* Snapshot mode + prompt id for the handler below. */
        furi_mutex_acquire(app->mtx, FuriWaitForever);
        ClaudeBuddyMode mode = app->mode;
        char id[48];
        strlcpy(id, app->prompt_id, sizeof(id));
        furi_mutex_release(app->mtx);

        if(mode != ClaudeBuddyModePrompt) continue;
        if(id[0] == '\0') continue;

        const char* decision = NULL;
        if(event.key == InputKeyOk) decision = "once";
        else if(event.key == InputKeyLeft) decision = "deny";
        if(!decision) continue;

        bool tx_ok = false;
        if(app->profile) {
            char json[160];
            int n = snprintf(
                json,
                sizeof(json),
                "{\"cmd\":\"permission\",\"id\":\"%s\",\"decision\":\"%s\"}\n",
                id,
                decision);
            if(n > 0 && (size_t)n < sizeof(json)) {
                tx_ok = claude_buddy_profile_tx(
                    app->profile, (const uint8_t*)json, (uint16_t)n);
            }
        }

        /* Dismiss modal locally regardless of TX result — user gets
         * immediate visual ack. Note the result on the status line so
         * they can distinguish "sent" from "tried but BLE refused". */
        furi_mutex_acquire(app->mtx, FuriWaitForever);
        app->mode = ClaudeBuddyModeNormal;
        app->prompt_id[0] = '\0';
        snprintf(
            app->hb_msg,
            sizeof(app->hb_msg),
            "sent: %s (%s)",
            decision,
            tx_ok ? "ok" : "fail");
        furi_mutex_release(app->mtx);
        view_port_update(app->view_port);
    }

    /* Teardown: stop drain thread, then tear down BLE, then GUI. */
    app->running = false;
    furi_thread_join(app->rx_thread);
    furi_thread_free(app->rx_thread);

    if(app->profile) {
        bt_profile_restore_default(app->bt);
    }
    bt_set_status_changed_callback(app->bt, NULL, NULL);
    furi_record_close(RECORD_BT);

    /* Make sure the LED is off when we leave. */
    notification_message(app->notifications, &sequence_reset_blue);
    furi_record_close(RECORD_NOTIFICATION);

    furi_timer_stop(app->redraw_timer);
    furi_timer_free(app->redraw_timer);
    gui_remove_view_port(app->gui, app->view_port);
    view_port_free(app->view_port);
    furi_record_close(RECORD_GUI);

    /* Animation after view_port — the icon-animation timer could have
     * fired a view_port_update between our gui_remove_view_port and
     * view_port_free. Stopping the animation first avoids that race. */
    if(app->current_anim) {
        icon_animation_stop(app->current_anim);
        icon_animation_free(app->current_anim);
    }

    furi_stream_buffer_free(app->rx_stream);
    furi_message_queue_free(app->input_queue);
    furi_mutex_free(app->mtx);
    free(app);
    return 0;
}
